### ISSUE TITLE
Replace "server" with "host"

### ISSUE THREAD

**Issue by herpdederp** [BoltEngine/Bolt-Tracker#1]
API is currently inconsistent about this

**Comment by herpdederp** [comment]
test

**Comment by herpdederp** [comment]
test

**Comment by ramonmelo** [comment]
"Server" is set as deprecated by the code, with a message to use "Host" instead.

**Comment by herpdederp** [comment]
These still need to be changed

server BoltNetwork
serverConnectionAcceptMode BoltConfig
serverConnectionLimit BoltConfig
serverDejitterDelay BoltConfig
serverDejitterDelayMax BoltConfig
serverDejitterDelayMin BoltConfig
ServerFrame
serverSendRate BoltConfig
serverTime BoltNetwork

**Comment by ramonmelo** [comment]
Fixed on: https://github.com/BoltEngine/bolt-internal/commit/830ed5b94c67008b475f3816a6801ecec4cacb14
