### ISSUE TITLE
`SessionListUpdated` is not called if there is no server (1.2.4)

### ISSUE THREAD

**Issue by ivanquirino** [BoltEngine/Bolt-Tracker#100]
### How to reproduce issue
1. Make sure there are no servers already started
2. `BoltLauncher.StarClient()`

### Expected Behavior
`SessionListUpdated` callback shoud be fired. This way I can shutdown and start as server if there is none.
In 1.2.0.3 this callback is called

### Actual behavior
The callback is ony fired if any server creates a room

### Configuration
- Unity Version: 2018.2.1
- Bolt Version: 1.2.4
- Operating System: Windows
- Network Configuration: Photon Cloud

**Comment by ramonmelo** [comment]
Hello, 

This was an erratic behavior, as the name implies, this event will occur only when the list has been updated when sessions are added or removed from the list. 
You can always check the `BoltNetwork.SessionList` to get the latest available sessions.
