### ISSUE TITLE
BoltNetwork.serverFrame doesnt reset back to 0 between shutdown/startup of Bolt

### ISSUE THREAD

**Issue by DirtyHippy00** [BoltEngine/Bolt-Tracker#102]
BoltCore::_frame is a static which is used by BoltNetwork.serverFrame.  It never gets reset back to 0.  So if you shut down the network and restart, the server frame will continue where it left off when the network shut down.

For consistency this field should be reset back to 0 when the network shuts down (or when it starts).

**Comment by ramonmelo** [comment]
Fixed on Bolt v1.2.6
