### ISSUE TITLE
SessionListUpdated not called anymore after connection attempt is refused

### ISSUE THREAD

**Issue by Hyperg** [BoltEngine/Bolt-Tracker#104]
### How to reproduce issue
1. Set Bolt connection accept mode to Manual (Window/Bolt/Settings/Connection -> Accept Mode);
2. Setup a simple server and client where the server refuses an incoming connection attempt (see attached script, which is a slightly modified version of the Bolt's sample script "bolt_samples\NEW-PhotonCloud\demo_simple\Scripts\PhotonInit.cs"
 
[TestNetworkManager.cs.txt](https://github.com/BoltEngine/Bolt-Tracker/files/2736101/TestNetworkManager.cs.txt)

### Expected Behavior
The client should continue to receive **SessionListUpdated** calls after the _ConnectRefused_ callback has been raised.

### Actual behavior
The client does not receive any **SessionListUpdated** calls anymore, after the _ConnectRefused_ callback is raised. Also the list of sessions from **BoltNetwork.SessionList** seems to be frozen to last contents before _ConnectRefused_ call.

### Configuration
- Unity Version: 2017.4.4f1
- Bolt Version: 1.2.0.3
- Operating System: Windows 10 x64
- Network Configuration: LAN, WAN

**Comment by ramonmelo** [comment]
Fixed on the next release (v1.2.8)

Thanks for your feedback.

**Comment by Hyperg** [comment]
Good news! The bug does bother our beta traffic quite a while (given we close the rooms when the matches start and it takes a while to update the room tokens, so the bug does occur quite often).
