### ISSUE TITLE
Exception thrown when restarting Bolt after a connection attempt is refused

### ISSUE THREAD

**Issue by Hyperg** [BoltEngine/Bolt-Tracker#105]
This issue cropped up while trying to come up with a workaround for issue #104 :

### How to reproduce issue
1. Set Bolt connection accept mode to Manual;
2. Setup a simple server which refuses incoming connections;
3. Setup as simple client which restarts Bolt in a coroutine when **ConnectRefused** is raised;

[TestNetworkManager.cs.txt](https://github.com/BoltEngine/Bolt-Tracker/files/2736241/TestNetworkManager.cs.txt)

### Expected Behavior
Bolt should restart normally

### Actual behavior
1. An exception is thrown:
`ObjectDisposedException: The object was used after being disposed.
System.Net.Sockets.Socket.BeginSendTo (System.Byte[] buffer, Int32 offset, Int32 size, SocketFlags socket_flags, System.Net.EndPoint remote_end, System.AsyncCallback callback, System.Object state)
udpkit.plataform.photon.puncher.Puncher+<SendRoutine>d__28.MoveNext ()
udpkit.plataform.photon.puncher.coroutine.RoutineManager.Service ()
udpkit.plataform.photon.puncher.Puncher.Service ()
udpkit.plataform.photon.puncher.PunchAPI.Service ()
udpkit.platform.photon.PhotonPoller.Update ()`

2. Global events seem to stop working properly after Bolt is restarted (some of them are raised on Client/Server, some are not)

### Configuration
- Unity Version: 2017.4.4f1
- Bolt Version: 1.2.0.3
- Operating System: Windows 10 x64
- Network Configuration: LAN, WAN

**Comment by ramonmelo** [comment]
Fixed on the next release (v1.2.8)

Thanks for your feedback.
