### ISSUE TITLE
No callback when client attempts to connect to recently shutdown server

### ISSUE THREAD

**Issue by Hyperg** [BoltEngine/Bolt-Tracker#106]
### How to reproduce issue
1. Setup a simple Bolt server which publishes a room to Photon cloud;
2. Setup a simple client which connects to Bolt Photon cloud rooms;
3. Start server;
4. Start client and wait for the session list to get updated (wait for the server to show up in client's room list);
5. Shutdown server and **immediately** make the client connect to that session (before the next SessionListUpdated call arrives);

[TestNetworkManager.cs.txt](https://github.com/BoltEngine/Bolt-Tracker/files/2736295/TestNetworkManager.cs.txt)

### Expected Behavior
The client should receive some form of error callback for connecting to a defunct session (_SessionConnectFailed_, _ConnectFailed_, etc).

### Actual behavior
The client does not receive any connect fail notification

### Configuration
- Unity Version: 2017.4.4f1
- Bolt Version: 1.2.0.3
- Operating System: Windows 10 x64
- Network Configuration: LAN, WAN

**Comment by supernikx** [comment]
Same problem, UP

**Comment by ramonmelo** [comment]
Fixed on Bolt v1.2.6.

**Comment by TheL94** [comment]
Same problem in 1.2.7

**Comment by supernikx** [comment]
nope, I'm using 1.2.7 and still not working

**Comment by ramonmelo** [comment]
Fixed on the next release (v1.2.8)

- When you attempt to connect to a nonexistent session, the `SessionConnectFailed` will be invoked.

Thanks for your feedback.
