### ISSUE TITLE
2018.3 Prefab Error

### ISSUE THREAD

**Issue by herpdederp** [BoltEngine/Bolt-Tracker#107]
Selecting a Bolt Entity in the hierarchy while playing in 2018.3+ results in the following error

InvalidOperationException: This cannot be used during play mode.
UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty (UnityEngine.SceneManagement.Scene scene) <0x40c29160 + 0x00052> in <0cfd8cff15e142bb8ab38109b16a9409>:0
BoltEditor.BoltPrefabUtility.MarkDirty (UnityEngine.Object obj, UnityEngine.SceneManagement.Scene scene, System.Boolean save) (at <e8d5a20949404623b523c52e3d527f80>:0)
BoltEditor.BoltPrefabUtility.MarkDirty (UnityEngine.GameObject gameObject, System.Boolean save) (at <e8d5a20949404623b523c52e3d527f80>:0)
BoltEntityEditor.DrawPrefabInfo (BoltEntity entity) (at <e8d5a20949404623b523c52e3d527f80>:0)
BoltEntityEditor.OnInspectorGUI () (at <e8d5a20949404623b523c52e3d527f80>:0)
UnityEditor.InspectorWindow.DoOnInspectorGUI (System.Boolean rebuildOptimizedGUIBlock, UnityEditor.Editor editor, System.Boolean wasVisible, UnityEngine.Rect& contentRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1625)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by herpdederp** [comment]
To clarify this happens in play mode in editor

**Comment by Tykev** [comment]
Fixed in v1.2.6
