### ISSUE TITLE
Photon Cloud Match Making Sample Errors

### ISSUE THREAD

**Issue by inspirednotion** [BoltEngine/Bolt-Tracker#109]
### How to reproduce issue
1. <step 1>Open Lobby scene and setup the Lobby manage to open your game scene. Se the player count required to 1 and set count in time to 3 seconds.
2. <step 2>Hit play create a room with a name, join.
3. <step 3>Once into the game with non errors, hit "Esc" and click on Back button.
4. <step 4>Create a room and you will be presented with first error
### Expected Behavior
I presume it should create a new room and connect in as the first time round.

### Actual behavior
Crashes out with an error (see image : error for details) 
If you then click cancel to the new connecting and then try the process again to create  new room throws a few more errors. Please see image error2.

It is somthing to do with closing/shutting down the server connection

### Configuration
- Unity Version: <Unity 2018.2.f6>
- Bolt Version: <Samples 1.25 downloaded from Github as directed to> Bolt version is current from Unity store. in the wizard it states bolt is version debug.1.2.5
- Operating System: <Win 10 pro>
- Network Configuration: <Virgin Media Fiber 200mb
![error](https://user-images.githubusercontent.com/3474590/52913388-a0d08400-32b5-11e9-8765-aae94a19bc28.PNG)
![error2](https://user-images.githubusercontent.com/3474590/52913390-aaf28280-32b5-11e9-8f7b-fd4b058c75a6.PNG)

>

**Comment by ramonmelo** [comment]
Hello @inspirednotion,

The Lobby Sample was refactored and the updated version is available on our [samples repo](https://github.com/BoltEngine/Bolt-Sample/tree/master/LobbyManager).

Please, have a look. Those issues were solved.
