### ISSUE TITLE
GlobalEventListener callback is called twice when another listener is destroyed

### ISSUE THREAD

**Issue by TSchmGIT** [BoltEngine/Bolt-Tracker#11]
### How to reproduce issue
1. Setup 3 (or more) unique GlobalEventListener
2. Provoke a "Disconnected()" callback and log each call.
3. Destroy a GlobalEventListener during one of these callbacks
### Expected Behavior

Each callback should execute. If the callback on the destroying listener is called first, the destroyed listener won't execute its code. Else both execute the callback
### Actual behavior

Without an error one of the existing callbacks is executed twice. It seems it replaced the call of the destroyed callback
### Configuration

Unity Version: 5.3.4f1
Bolt Version: 0.4.3.11
Operating System: Win 10

**Comment by ramonmelo** [comment]
This behavior is not shown on the current version.
