### ISSUE TITLE
OpJoinLobby is only allowed when connected to a Master Server. Current Server: GameServer, current State: Leaving

### ISSUE THREAD

**Issue by DanielSnd** [BoltEngine/Bolt-Tracker#114]
**Host-Side Log:**
[Issue114_Host-Side-Log.txt](https://github.com/BoltEngine/Bolt-Tracker/files/3080591/Issue114_Host-Side-Log.txt)
**Client-Side Log:**
[Issue114_Client-Side-Log.log](https://github.com/BoltEngine/Bolt-Tracker/files/3080592/Issue114_Client-Side-Log.log)

### How to reproduce issue
I can't reproduce it at all. It only happens to 3 players of my game so far. One of them has reported being able to connect to other games except for under the same network the other computer is in, another can't connect to any games at all, another hasn't reported back.

> **ULGRATH Last Saturday at 7:39 PM**
> hey guys since the update I am no longer able to connect to multiplayer?
> getting an invalid peration exception collection modified; enumeration operation may not execute
> and opjoinlobby is only allowed when conneted to a master server. current server, game server, current state: leaving
> any ideas?

> **theskywitch Last Saturday at 10:32 PM**
> i'm having the same error messages as @ULGRATH however i'm using MAC. I've included my Player.log and WebPlayer.log as well.
> Error messages: 
> "InvalidOperationException: Collection was modified; enumeration operation may not execute." 
> "OpJoinLobby is only allowed when connected to a Master Server. Current Server: GameServer, current State: Leaving"

> **Value Yesterday at 12:28 PM**
> What is this?
![840010_screenshots_20190414212653_1](https://user-images.githubusercontent.com/9072324/56140945-b75f2880-5f50-11e9-946d-bb9a5d18cee7.jpg)

> **theskywitch Yesterday at 6:04 PM**
> Hiya i'm still getting the same error messages and can't connect to multiplayer still. Attached are my player and webplayer logs.

> **ULGRATH Yesterday at 7:22 PM**
> I have a feeling the unable to connect in multiplayer has to do with ports just a guess though.
> I can connect to others however cannot connect locally behind the router

> **theskywitch Yesterday at 9:28 PM**
> I haven't tried local multiplayer. i've only been doing multiplayer through wifi/long distance, which i've been having issues with.
> @ULGRATH  you're able to play garden paws through wifi/long distance?

### Expected Behavior
Player receives Session List, clicks on one of the sessions received, joins the game and is happy.

### Actual behavior
> BOLT START DONE
> (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
> 
> OpJoinLobby is only allowed when connected to a Master Server. Current Server: GameServer, current State: Leaving
>  
> (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
> 
> Uploading Crash Report
> InvalidOperationException: Collection was modified; enumeration operation may not execute.
>   at System.Collections.Generic.Dictionary`2+Enumerator[TKey,TValue].MoveNext () [0x00016] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 
>   at udpkit.plataform.photon.coroutine.RoutineManager.Service () [0x00097] in <3286b14ac13e43aabf7dd507f453b344>:0 
>   at udpkit.platform.photon.PhotonPoller.Update () [0x00056] in <3286b14ac13e43aabf7dd507f453b344>:0 
>  
> (Filename: <d7ac571ca2d04b2f981d0d886fa067cf> Line: 0)
> 
> Failed to Connect to: Photon / pleaseE PLEASEEEEEEE (cdc88fa3-2aee-47a7-8ffa-230548f652f4)

### Configuration
- Unity Version: 2018.2.21f
- Bolt Version: 1.2.8
- Operating System: In the case of this log the client is using OSX, but I have another log from another client that uses Windows with the same problem.
- Network Configuration: ????

**Comment by DanielSnd** [comment]
New logs with the bolt debugs in it.

[Output_Log_Ulgrath_SERVER.txt](https://github.com/BoltEngine/Bolt-Tracker/files/3099181/Output_Log_Ulgrath_SERVER.txt)
[Output_Log_Ulgrath_CLIENT.txt](https://github.com/BoltEngine/Bolt-Tracker/files/3099182/Output_Log_Ulgrath_CLIENT.txt)

It seems that it keeps pinging and eventually fails and disconnects. I don't think it's considering that the NAT Punchthrough failed and falling back to Relay at all.

**Comment by DanielSnd** [comment]
From another player with the problem, this is what they sent to me after testing an fresh test build I sent them:

> When I'm hosting the room, photon pulls the IP of the first network adapter:

![2019-04-19_20_24_55-GardenPaws_Server](https://user-images.githubusercontent.com/9072324/56441814-24512600-62a3-11e9-83ca-e8db52f779a4.png)

![NICs_Server](https://user-images.githubusercontent.com/9072324/56441833-303ce800-62a3-11e9-8a58-62a713fa2a5d.png)

> I **_think_** that's advertised to the client, which then tries to connect (via LAN) to a host via an IP that's not routed:

![Client_Connect](https://user-images.githubusercontent.com/9072324/56441849-3c28aa00-62a3-11e9-8d77-1e2319d19dbc.png)

> Photon's doing a great job here btw :3 I'm not really Unity-savvy but I'd have expected the client to go straight for the WAN IP (89.245....)

**Comment by ramonmelo** [comment]
Thanks for the feedback.

Fixed on the next release.
