### ISSUE TITLE
BoltShutdownBegin - UdpConnectionDisconnectReason always return Disconnected (3)

### ISSUE THREAD

**Issue by ByvDeveloper** [BoltEngine/Bolt-Tracker#115]
### How to reproduce issue
1. Create server on first device
2. Connect to server on second device
3. Disable WI-FI (or unplug network cable from PC)

### Expected Behavior
Must return UdpConnectionDisconnectReason.Timeout

### Actual behavior
Returns UdpConnectionDisconnectReason.Disconnected
### Configuration
- Unity Version: 2018.1.0f2
- Bolt Version: 1.2.8
- Operating System: MAC OS

**Comment by ramonmelo** [comment]
Thanks for the feedback.

Fixed on the next release.
