### ISSUE TITLE
Scripting runtime version ".Net 4.x Equivalent" bug

### ISSUE THREAD

**Issue by ByvDeveloper** [BoltEngine/Bolt-Tracker#116]
### How to reproduce issue
1. Change platform to Android
2. Change "Scripting runtime version" to .Net 4.x
3. Build application and start as client (Call StartClient())

When I try to start client on my android device with mobile internet (not wi-fi) I get error: Connect() to 'ns.exitgames.com' (InterNetworkV6) failed: System.Net.Sockets.SocketException (0x80004005): Network is unreachable

I'ts only on .Net 4.x. 
.Net 3.5 - no problem

### Configuration
- Unity Version: 2018.1.0f2
- Bolt Version: 1.2.7
- Operating System: Android
- Network Configuration: Mobile network (Kyivstar)

**Comment by ramonmelo** [comment]
Hello @ByvDeveloper,

I've executed a few tests here and found no issues. Does this still occur on your end?

However, I was able to reproduce your error *only* when the Android device has no internet connection at all. No wi-fi, no mobile data network.
In this case, the Photon Cloud can't be reached, and the Bolt will shutdown.

**Comment by JohnTube** [comment]
Hi @ByvDeveloper,

Could you help us find out the root cause for this?
See my questions and findings [here](https://forum.photonengine.com/discussion/13431/pun-2-automatically-disconnected-in-android-device).
Your help is much-appreciated, thanks!

**Comment by JohnTube** [comment]
Hi @ByvDeveloper,

Are you OK to test a different Photon3Unity3d.dll?

**Comment by ByvDeveloper** [comment]
@JohnTube Hi. After update to bolt 1.2.9 this error was solved. Thx.
