### ISSUE TITLE
GlobalEventListener not called after restart

### ISSUE THREAD

**Issue by ByvDeveloper** [BoltEngine/Bolt-Tracker#117]
### How to reproduce issue
1. Call StartClient()
2. Call Shutdown();
3. Call StartClient() or StartServer()
4. Try receive any custom event in GlobalEventListener (OnEvent)

If disable and enable a gameobject (SetActive(false); SetActive(true)) with script, inherited from GlobalEventListener the problem will be solved.

### Configuration
- Unity Version: 2018.1.0
- Bolt Version: 1.2.8

**Comment by ramonmelo** [comment]
@ByvDeveloper ,

Have you tried to override the `PersistBetweenStartupAndShutdown()` on your `GlobalEventListener` ?

https://doc-api.photonengine.com/en/bolt/current/class_bolt_internal_1_1_global_event_listener_base.html#af082a91e959e610279268bd0c8af571b
