### ISSUE TITLE
Crash after a long pause [as server]

### ISSUE THREAD

**Issue by ByvDeveloper** [BoltEngine/Bolt-Tracker#118]
1. Call StartServer()
2. Set unity on pause or click on block button on android device
3. Wait 90 seconds
4. Uncheck pause.

Why can it be?

**Android device**
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/49681421/56217710-5e84b280-606c-11e9-8d2e-0c6de4fbb666.png">

**Unity**
<img width="606" alt="image" src="https://user-images.githubusercontent.com/49681421/56218038-f1255180-606c-11e9-8874-d932d5d0567c.png">

BoltShutdown with timeout reason is called before that.
Also **not called** "Started background Photon keepalive" in my project

**Comment by ramonmelo** [comment]
Photon Bolt with the Photon Cloud integration (Free version) is built on top of a custom implementation of Photon Realtime. 

If you look at the [known issues page](https://doc.photonengine.com/en-us/realtime/current/troubleshooting/known-issues), you will see that one of them is related to pausing the game and maintaining a connection with the server. This is not really an issue of Photon Realtime or Bolt but is mainly related to how the application works on mobile devices.

We try to mitigate this issue by running background threads to send/receive acknowledge messages to the server, but we still depend on the OS to keep them running.

Considering that the connection was ceased mid-pause, in consequence of the lack of data exchange between the peer and the server, the internal LoadBalancingClient is disconnected by timeout, and that is really what you receive via the callback, as you already stated.

Also, the Bolt network loop depends on the game loop of Unity, which simply doesn't run when the application is in the background or paused. Which causes any commands/events/state transfer accumulate waiting for packages acknowledge from the other end of the connection (server waiting for the client or vice versa), leading to package overflow and a proper shutdown (equally using the timeout as disconnect reason).

You can increase the `Timeout` configuration on the `Bolt Settings` window, and let the peer wait more before being dropped, but this can result in cases where the player really loses connection, so the server/client will be wasting time waiting for the player.

In both cases, you can always just restart the peer and connect again.

The log message "Started background Photon keepalive" was removed on the latest version.
