### ISSUE TITLE
GlobalEventListener has not virtual OnEnable, OnDisable

### ISSUE THREAD

**Issue by ByvDeveloper** [BoltEngine/Bolt-Tracker#119]
### How to reproduce issue
1. Create script, inherited from GlobalEventListener
2. Declare method void OnEnable() or OnDisable()

### Expected Behavior
Declare OnEnable/OnDisable as public virtual void OnEnable/OnDisable

### Actual behavior
Warning: 'NetworkManager.OnEnable()' hides inherited member 'GlobalEventListenerBase.OnEnable()'. Use the new keyword if hiding was intended. (CS0108) [Assembly-CSharp]

**Comment by ramonmelo** [comment]
Hello @ByvDeveloper,

On the `GlobalEventListener` we use the `OnEnable` and `OnDisable` callbacks to setup the internal events for a particular instance of this class. This way, you only need to call the base method in order to maintain Bolt working as expected, as shown below:

```csharp
public class NetworkCallbacks : Bolt.GlobalEventListener
{
    new void OnEnable()
    {
        base.OnEnable();
        // My custom code
    }

    new void OnDisable()
    {
        base.OnDisable();
        // My custom code
    }
}
```
