### ISSUE TITLE
[BoltGlobalBehaviour("scene")] not working without BoltNetworkMode

### ISSUE THREAD

**Issue by 0x-1** [BoltEngine/Bolt-Tracker#12]
### How to reproduce issue
1. create a class and inherit: Bolt.GlobalEventListener
2. add [BoltGlobalBehaviour("test")] to the class
3. debug.logerror("success") in a public override void SceneLoadLocalDone
### Expected Behavior

"success" error message in scene "test"
### Actual behavior

no error message
### Configuration

Unity Version: 5.3.4f1
Bolt Version: 0.4.3.13
Operating System: Win10x64

**Comment by fholm** [comment]
This should be fixed in all bolt version after 1.0.0.0, closing for now.
