### ISSUE TITLE
Logs reveal app-id when debugging.

### ISSUE THREAD

**Issue by DanielSnd** [BoltEngine/Bolt-Tracker#120]
### How to reproduce issue
1. Setup debugging
2. Connect and look at the logs

### Expected Behavior
No one should be able to know my app-id.

### Actual behavior
Whoever looks at the logs knows my app-id thanks to the line "Connecting to Photon Cloud using AppId: "

**Comment by ramonmelo** [comment]
Fixed on the next release.
