### ISSUE TITLE
StartClient&Shutdown bolt exception

### ISSUE THREAD

**Issue by ByvDeveloper** [BoltEngine/Bolt-Tracker#121]
### How to reproduce issue
```
if(!BoltNetwork.IsRunning)
{
    BoltLauncher.StartClient();
}

if(BoltNetwork.IsRunning)
{
    BoltLauncher.Shutdown();
}
if(!BoltNetwork.IsRunning)
{
    BoltLauncher.StartClient();
}
if(BoltNetwork.IsRunning)
{
    BoltLauncher.Shutdown();
}
```

If call "shutdown" while bolt starting or call startclient while bolt shutting down an error occurs:
- BoltException: Bolt is already running, you must call BoltLauncher.Shutdown() before starting a new instance of Bolt.
or
- BoltException: Bolt is not running so it can't be shutdown

Is it possible to disable it if debug mode is off?

### Configuration
- Unity Version: 2018.1.0f2
- Bolt Version: 1.2.8

**Comment by ramonmelo** [comment]
Thanks for your feedback!

Fixed on the next release.
