### ISSUE TITLE
Platform Instantiation calling twice

### ISSUE THREAD

**Issue by ByvDeveloper** [BoltEngine/Bolt-Tracker#122]
### How to reproduce issue
1. StartClient()
2. Click on pause (unity editor) or hide application (android)
3. Wait first message ">>>> [PUNCH] >>>> Platform Instantiation"
4. Unpause or open application

### Expected Behavior
Check is instantiation already started before call Platform Instantiation.

### Actual behavior
[PUNCH] >>>> Platform Instantiation calling twice, as consequence got error: BoltException: Bolt is already running, you must call BoltLauncher.Shutdown() before starting a new instance of Bolt, because bolt already starting.
It's problem actual for weak mobile device, when game "freezing" while scene loading.

### Configuration
- Unity Version: 2018.1.0f2
- Bolt Version: 1.2.8

**Comment by ramonmelo** [comment]
Thanks for the feedback!

Fixed on the next release.
