### ISSUE TITLE
Null reference "BoltCore.DisableLanBroadcast ()"

### ISSUE THREAD

**Issue by ByvDeveloper** [BoltEngine/Bolt-Tracker#124]
### How to reproduce issue
1. Call "BoltNetwork.Connect" on some devices

### Error:
NullReferenceException: Object reference not set to an instance of an object BoltCore.DisableLanBroadcast ()
BoltCore.Connect (UdpKit.UdpSession session, IProtocolToken token)
BoltNetwork.Connect (UdpKit.UdpSession session, IProtocolToken token)

About 1,2k users got this error (Analytics data) for a week

(Same problem like #39)

### Configuration
- Unity Version: 2018.1.0f2
- Bolt Version: 1.2.8

**Comment by ramonmelo** [comment]
Hello @ByvDeveloper,

Could you elaborate more about what you mean by "some devices"?
Are you enabling the LAN Broadcast (calling `BoltNetwork.EnableLanBroadcast()`) before trying to connect to the server?
Do you have any complete log of when this occurs (from both server and client)?

**Comment by ByvDeveloper** [comment]
Hello, @ramonmelo. No, i'm not using EnableLanBroadcast or DisableLanBroadcast (maybe it's internal call). And i'm not have logs, cause it's errors i'm got from analytics data (firebase).
Last time got this error 2 hours ago (Galaxy J6+, Android 9, Bolt 1.2.9).
I and our testers personally have never been able to reproduce this error.

**Comment by ramonmelo** [comment]
Thanks for your feedback!

Fixed on the next release.
