### ISSUE TITLE
Photon Bolt Does Not Start Server or Client on Standalone Build

### ISSUE THREAD

**Issue by arasaydogan** [BoltEngine/Bolt-Tracker#125]
### How to reproduce issue
This issue arising from STANDALONE build, there is no error in the unity editor.

1. <step 1> following guide on the official bolt documentation: https://forum.photonengine.com/discussion/6740/following-tutorial-cant-find-next-scene
2. <step 2> calling BoltLauncher.StartServer();  or BoltLauncher.StartClient(); on the standalone build
3. <step 3> Initialization Error

Tried to move "BoltStartDone()" function under NetworkCallbacks class, result is the same

note: NAT is open

### Expected Behavior
Start server or join as a client

### Actual behavior
output_log:

Initialization Error
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
BoltNetworkInternal:Initialize(BoltNetworkModes, UdpEndPoint, BoltConfig, UdpPlatform, String)
BoltLauncher:Initialize(BoltNetworkModes, UdpEndPoint, BoltConfig, String)
BoltLauncher:StartServer(UdpEndPoint, BoltConfig, String)
BoltLauncher:StartServer(UdpEndPoint, String)
BoltLauncher:StartServer(Int32)
LobbyManager:Server() (at C:\Users\aaydogan\Documents\Unity Projects\PlayfabPhotonBolt\Assets\00_Scripts\LobbyManager.cs:11)
UnityEngine.Events.InvokableCall:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.UI.Button:Press() (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\UI\Core\Button.cs:66)
UnityEngine.UI.Button:OnPointerClick(PointerEventData) (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\UI\Core\Button.cs:108)
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData) (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\EventSystem\ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1) (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\EventSystem\ExecuteEvents.cs:261)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData) (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\EventSystem\InputModules\StandaloneInputModule.cs:613)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32) (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\EventSystem\InputModules\StandaloneInputModule.cs:510)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent() (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\EventSystem\InputModules\StandaloneInputModule.cs:490)
UnityEngine.EventSystems.StandaloneInputModule:Process() (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\EventSystem\InputModules\StandaloneInputModule.cs:254)
UnityEngine.EventSystems.EventSystem:Update() (at C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\EventSystem\EventSystem.cs:377)
 
(Filename: C:/Users/aaydogan/Documents/Unity Projects/PlayfabPhotonBolt/Assets/00_Scripts/LobbyManager.cs Line: 11)

Skipping profile frame. Receiver can not keep up with the amount of data sent
 
(Filename: C:\buildslave\unity\build\Modules/Profiler/Public/Profiler.cpp Line: 927)

Skipping profile frame. Receiver can not keep up with the amount of data sent
 
(Filename: C:\buildslave\unity\build\Modules/Profiler/Public/Profiler.cpp Line: 927)

### Configuration
- Unity Version: <version> 2018.4.1f1
- Bolt Version: <version> v1.2.8
- Operating System: <OS> Windows 10 x64
- Network Configuration: <config> LAN

**Comment by herpdederp** [comment]
It isn't clear what step 3 means, can you clarify or upload a repro project?
Do you have managed stripping on?

**Comment by arasaydogan** [comment]
> It isn't clear what step 3 means, can you clarify or upload a repro project?
> Do you have managed stripping on?

No, it is disabled, i changed the issue statements, i can upload the repo today

**Comment by arasaydogan** [comment]
I find the issue, im using "Obfuscator" and "Anti-Cheat Toolkit" assets, when i open up fresh new project and not include them, issue has gone. But i should use them for security, how can i handle with this situation?

**Comment by herpdederp** [comment]
Can you determine which is causing the issue?

**Comment by arasaydogan** [comment]
I imported Obfuscator asset only and caused this problem again, the reason that i want to use them is to protection against modders, hackers easily can mod apks, and they did to my game, so what about photon protection? Are unsigned apks can connect to server and eat my ccu? how can i protect my connection against modders?

**Comment by herpdederp** [comment]
We can take a look at the issue and see if it is an issue on our end we can fix or something you should talk to the developer about. 

We'll soon allow different types of verification like PUN does for Steam, Oculus, Viveport, etc.

In addition, if you have dedicated servers, they can currently verify the Steam, Playfab, etc session ticket and accept/reject connection based on that.

**Comment by arasaydogan** [comment]
thank you so much, i will make a contact with the asset developer. So you say that modded users can easily connect photon cloud servers, there is no protection layer, this is bad for me. And i will integrate Playfab to my game, i think they can't use in app purchase items without Playfab verification, isn't it?

**Comment by herpdederp** [comment]
" So you say that modded users can easily connect photon cloud servers, there is no protection layer, this is bad for me"
See my last post, all of those methods work for preventing this.

"And i will integrate Playfab to my game, i think they can't use in app purchase items without Playfab verification, isn't it?"
There are many ways to do in app purchases, Playfab is one option.

**Comment by arasaydogan** [comment]
Aw ok sorry, i though you are currently working on this verifications, thank you so much!
