### ISSUE TITLE
ThreadAbortException (StartServer & StartClient)

### ISSUE THREAD

**Issue by ByvDeveloper** [BoltEngine/Bolt-Tracker#126]
### How to reproduce issue
1. Setup Unity 2019.1.5f1
2. Change scripting backend IL2CPP and .Net 4.0
2. Call "StartServer" or "StartClient"

### Actual behavior
Got error: 
ThreadAbortException
  at ExitGames.Client.Photon.SupportClass+<>c__DisplayClass6_0.<StartBackgroundCalls>b__0 () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ThreadStart.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ContextCallback.Invoke (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0 
  at System.Threading.ThreadStart.Invoke () [0x00000] in <00000000000000000000000000000000>:0 
System.UnhandledExceptionEventHandler:Invoke(Object, UnhandledExceptionEventArgs)
 
(Filename: currently not available on il2cpp Line: -1)

### Configuration
- Unity Version: 2019.1.5f1
- Bolt Version: 1.2.8

**Comment by ramonmelo** [comment]
Which is the target of your build?

**Comment by ByvDeveloper** [comment]
Moving to Unity 2019. It not support another backend

**Comment by JohnTube** [comment]
Hi @ByvDeveloper,

What is your target platform? Android?
See my post [here](https://forum.photonengine.com/discussion/comment/45946/#Comment_45946).

We think that this is a Unity bug.
Update Unity and try to reproduce.

**Comment by ByvDeveloper** [comment]
@JohnTube Yes, Android. And Unity 2019.1.5, but bug still exists.

**Comment by JohnTube** [comment]
Hi @ByvDeveloper

How can I reproduce?
Do you have minimal 100% repro steps?
Or maybe minimal repro project?

**Comment by ByvDeveloper** [comment]
@JohnTube Huawei P Smart, Huawei P Smart +, Xiaomi redmi note 5
Android 8.0, Android 8.1

**Comment by Tobias-EG** [comment]
I could reproduce the issue and fix it in the Photon3Unity3d.dll.
An update is pending.

**Comment by JohnTube** [comment]
Hey @ByvDeveloper,

ICYMI:

[PUN 2.13](https://assetstore.unity.com/packages/tools/network/pun-2-free-119922) is out with a new library v4.1.2.16 in its changelog:

> Fixed: Each thread created via SupportClass.StartBackgroundCalls will now try-catch a ThreadAbortException. Apparently, the handling of a ThreadAbortException changed with Unity 2019, which started to log the exceptions on IL2CPP, 4.x runtime.

If you do not want to wait for Bolt 1.2.9 you can download PUN2 and import only the lib ("Assets/Photon/PhotonLibs/Photon3Unity3d.dll")

**Comment by ramonmelo** [comment]
Thanks for the feedback! 

Fixed on the next release.
