### ISSUE TITLE
Two iOS players on WiFi not connecting

### ISSUE THREAD

**Issue by blistick** [BoltEngine/Bolt-Tracker#127]
**Describe the bug**
We have a simple Bolt app whose only purpose at this point is to establish a game session and allow multiple players to join. In a test with two iOS devices on the same WiFi network, with one acting as the host (to establish the server) and the other acting as a guest, we find that when the "NAT punchthrough" setting is enabled the guest player cannot connect. (If NAT punchthrough is disabled, however, the guest player can connect.) 

**To Reproduce**
Because the app is not public it is not possible for others to reproduce the issue, however I have attached console logs from the host app and guest app from a session where the issue occurred.

**Expected behavior**
We expect the guest player to be able to connect with the host player. 

**Actual behavior**
The guest player cannot connect with the host player.

**Screenshots**
The attached htm files contain a screenshot and console log. 
[console_logs.zip](https://github.com/BoltEngine/Bolt-Tracker/files/3298354/console_logs.zip)

**Desktop (If applicable, please complete the following information):**
N/A

**Smartphone (If applicable, please complete the following information):**
Host player: iPhone XR, iOS 12.3.1
Guest player: iPad 3, iOS 9.3.5  

**Additional context**
- Unity Version: 2018.3.12f1
- Bolt Version: Debug 1.2.8
- Network Configuration: WiFi from basic Linsys router

**Comment by ramonmelo** [comment]
Hello @blistick,

Could you try to increase the `Room Join Timeout` in the Bolt Settings?

On your log, you can see: `6/15/2019 4:54:47 PM: Room Join failed due to exceeded max time to join`, so increasing this value may solve your issue.

This setting will be set to 20s by default, instead of the 10s that is set on Bolt v1.2.8.

**Comment by blistick** [comment]
I increased the timeout to 30 seconds and it worked. The player connected after about 17-20 seconds. Thanks @ramonmelo! I will close the ticket.
