### ISSUE TITLE
UdpPacked WriteString and ReadString produce strings with different characters

### ISSUE THREAD

**Issue by xDura** [BoltEngine/Bolt-Tracker#128]
**Describe the bug**
Using UdpPacked WriteString(s)  and WriteString ends up in different string for the receiver.
On my case "Xavi Durà" was received by clients as "Xavi Dur?" and "David León" as "David Le?n" 

**To Reproduce**
1. use this token:

    public class UserDataToken : IProtocolToken
    {
        public string s;

        public void Read(UdpPacket packet)
        {
            s = packet.ReadString();
        }

        public void Write(UdpPacket packet)
        {
            packet.WriteString(s);
        }
    }

2. send this token
UserDataToken token = new UserDataToken();
token.s = "Xavi Durà"

3. Check the string on the client

**Expected behavior**
received string is equal to the one sent

**Actual behavior**
received string is different to the one sent

**Screenshots**

**Desktop (If applicable, please complete the following information):**
 - OS: [Windows 10]

**Additional context**
- Unity Version: [2019.1.3f1]
- Bolt Version: [v1.2.8]

**Comment by ramonmelo** [comment]
Hello @xDura,

I've extensively tested the Token serialization behavior, and I was not able to reproduce your behavior. 

On your description, you say: "send this token", which can be interpreted in several ways:
- Send as a connection token;
- Send as a parameter of an event (that can be to an entity or global);
- Send as a Command Token;
- Send as a parameter of a Command input;
- Send as a parameter of a Command result;
- etc.

Here is a simple test case in which I've tried to cover most of these cases, and on all of them, I was able to receive the Token with its data as expected.

Could you run this test on your end and report the results?

In the zip you will find:
1. The `project.json` with some simple Assets and;
2. An Unity package with the scripts/scenes/prefabs to test these cases.

Link: https://www.dropbox.com/s/qca32ttj0vgve9j/encoding_token.zip?dl=0

Let me know if I'm missing some detail.

**Comment by xDura** [comment]
Hi @ramonmelo I found a bug and it was totally our fault!
 
I tested with UTF-32 and UTF-8 and it works fine. Sorry and Big thanks!

**Comment by ramonmelo** [comment]
Hello @xDura,

Great that it's working fine, we are glad to help.
