### ISSUE TITLE
BoltNetwork.RegisterTokenClass

### ISSUE THREAD

**Issue by vinhui** [BoltEngine/Bolt-Tracker#13]
BoltNetwork.RegisterTokenClass will give a dictionary key already exists error when its already registered.
### How to reproduce issue
1. Call BoltNetwork.RegisterTokenClass<TestToken>() twice
2. Error
### Expected Behavior

Tell us what should happen
I would expect it would just catch the error and not throw it.
### Configuration

Unity Version:
Bolt Version: 0.4.3.11
Operating System:
Network Configuration:

**Comment by vinhui** [comment]
Already created a pull request with a fix

**Comment by Zerebokep** [comment]
Just a little suggestion, maybe it's a quick change, but in my opinion the RegisterToken method should be also available before launching bolt, so we could register them directly after launching the game instead to wait for the BoltStarted callback.

**Comment by herpdederp** [comment]
@vinhui Link to pull request?

**Comment by vinhui** [comment]
Well, the fork is gone since the source repo is gone...
