### ISSUE TITLE
Compile error in release mode

### ISSUE THREAD

**Issue by ShawnFPG** [BoltEngine/Bolt-Tracker#131]
**Describe the bug**

After switching to the bolt release mode, unity cannot making build anymore due to the error below:

> Unable to update following assemblies:Assets/Photon/PhotonBolt/assemblies/bolt.user.dll (Name = bolt.user, Error = 131) (Output: C:\Users\Nick\AppData\Local\Temp\tmp3dbaa11c.tmp)
> 
> Mono.CompilerServices.SymbolWriter.MonoSymbolFileException: Symbol file `Assets/Photon/PhotonBolt/assemblies/bolt.user.dll.mdb' does not match assembly
> 
>   at Mono.CompilerServices.SymbolWriter.MonoSymbolFile.ReadSymbolFile (System.String mdbFilename, System.Guid assemblyGuid) [0x00029] in <42af2190f59f4f56803a83e1b03d02ee>:0 
> 
>   at Mono.Cecil.Mdb.MdbReaderProvider.GetSymbolReader (Mono.Cecil.ModuleDefinition module, System.String fileName) [0x00019] in <42af2190f59f4f56803a83e1b03d02ee>:0 
> 
>   at Mono.Cecil.ModuleReader.ReadSymbols (Mono.Cecil.ModuleDefinition module, Mono.Cecil.ReaderParameters parameters) [0x00032] in <a3989f8c34e6476eaca56644d5639ee8>:0 
> 
>   at Mono.Cecil.ModuleReader.CreateModule (Mono.Cecil.PE.Image image, Mono.Cecil.ReaderParameters parameters) [0x00081] in <a3989f8c34e6476eaca56644d5639ee8>:0 
> 
>   at Mono.Cecil.ModuleDefinition.ReadModule (Mono.Disposable`1[T] stream, System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x0000d] in <a3989f8c34e6476eaca56644d5639ee8>:0 
> 
>   at Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x0006c] in <a3989f8c34e6476eaca56644d5639ee8>:0 
> 
>   at Mono.Cecil.AssemblyDefinition.ReadAssembly (System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x00000] in <a3989f8c34e6476eaca56644d5639ee8>:0 
> 
>   at AssemblyUpdater.Core.AssemblyUpdaterContext.ReadAssembly (System.String assemblyPath, APIUpdater.Framework.Log.IAPIUpdaterListener listener, System.IO.FileAccess mode, System.String[] searchPaths) [0x00084] in <3d08e38cad464844be4559b5f560883a>:0 
> 
>   at AssemblyUpdater.Core.AssemblyUpdaterContext.From (System.String assemblyPath, APIUpdater.Framework.Configuration.ConfigurationProvider configuration, System.String[] assemblySearchPaths, AssemblyUpdater.Core.UpdaterMode mode, APIUpdater.Framework.Log.IAPIUpdaterListener listener) [0x00025] in <3d08e38cad464844be4559b5f560883a>:0 
> 
>   at AssemblyUpdater.Core.AssemblyUpdaterContext.From (System.String assemblyPath, System.String[] assemblySearchPaths, AssemblyUpdater.Core.UpdaterMode mode, APIUpdater.Framework.Log.IAPIUpdaterListener listener) [0x00001] in <3d08e38cad464844be4559b5f560883a>:0 
> 
>   at AssemblyUpdater.Application.Program+<>c__DisplayClass0_0.<Main>b__1 (AssemblyUpdater.Application.UpdateOptions o) [0x0001f] in <3d08e38cad464844be4559b5f560883a>:0 
> 
>   at CommandLine.ParserResultExtensions.WithParsed[T] (CommandLine.ParserResult`1[T] result, System.Action`1[T] action) [0x0001e] in <5f6458f0234f43a48c09047109c24684>:0 
> 
>   at AssemblyUpdater.Application.Program.Main (System.String[] args) [0x00046] in <3d08e38cad464844be4559b5f560883a>:0 
> 
> Following assemblies were successfully updated but due to the failed ones above they were ignored (not copied to the destination folder).

**To Reproduce**

1. Making a build under the bolt debug mode
2. Switch to bolt release mode
3. Click the bolt compile button
4. Try to build after compile

**Expected behavior**

Unity should spit out a health build.

**Actual behavior**

The building process will be interrupted due to the error above.

**Configuration**

* Unity Version: 2019.1.10f1
* Bolt Version: 1.2.9
* Operating System: Win10 
* Network Configuration: N/A

**Additional context**

A workaround will be, find and delete the "bolt.user.dll.mdb" file

**Comment by ramonmelo** [comment]
Thanks for your feedback!

Fixed on the next release.
