### ISSUE TITLE
Restructure of Bolt causing VSCode warnings (CS0436)

### ISSUE THREAD

**Issue by Leedotzip** [BoltEngine/Bolt-Tracker#134]
I've been getting warnings in VSCode similar to other users (who posted in Discord) in regards to warning `CS0436` which I believe is due to a structure change in Bolt and compiled assemblies. 

Compiler Warning
```
The type 'GlobalEventListener' in `<path>\Temp\bolt\project.cs' conflicts with the imported type 'GlobalEventListener' in 'PhotonRealtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in '<path>\Temp\bolt\project.cs'. (CS0436) [Assembly-CSharp]
```

Example Code
```
public class NetworkCallbacks : Bolt.GlobalEventListener
{
    public override void SceneLoadLocalDone(string map)
    {
        BoltNetwork.Instantiate(BoltPrefabs.CharacterEntity, Vector3.zero, Quaternion.identity);
    }
}
```

Ugly Editor Highlighting Screencap
https://gyazo.com/1f9e4b198164dd985516fd8360056444

### How to reproduce issue
1. Install Bolt 1.2.9
2. Inherit from Bolt.GlobalEventListener
3. See warning on type `GlobalEventListener`

### Expected Behavior
No compiler warnings

### Configuration
- Visual Studio Code
- Unity Version: 2019.1
- Bolt Version: 1.2.9

**Comment by ramonmelo** [comment]
Thanks for your feedback!

Fixed on the next release.
