### ISSUE TITLE
Make the current PhotonRegion visible from the API 

### ISSUE THREAD

**Issue by Berbecarul** [BoltEngine/Bolt-Tracker#135]
**Describe the bug**
There is no way of finding to which region Bolt has connected after starting in "Best Region"

**To Reproduce**
1. Select "[best] Best Region" in bolt settings OR set PhotonRegion to "BEST_REGION" trough API
2. Start Bolt
  
**Expected behavior**
Bolt connects to a region that is visible from the API

**Actual behavior**
The current region that Bolt has connected to is not visible.
  
**Additional context**
- Unity Version: [2017.4.25f1]
- Bolt Version: [1.2.8]

**Comment by ramonmelo** [comment]
Thanks for your feedback!

Available in the next release.
