### ISSUE TITLE
Reliable Streaming

### ISSUE THREAD

**Issue by herpdederp** [BoltEngine/Bolt-Tracker#136]
Reliable Streaming currently has a number of issues

Notes for internal use:
https://app.asana.com/0/search/1135809601819441/229937468608642
https://app.asana.com/0/search/1135809601819441/229724068161628

**Comment by martindevans** [comment]
We want to send some blobs of data (just `byte[]`) reliably but with streaming being broken that looks to be very tricky. The only way I can see to do it right now is to base64 encode it and send it as strings in a reliable event which is _really_ messy (creates a lot of garbage for every packet). Is there a better alternative?

**Comment by herpdederp** [comment]
With events you can send it as binarydata 
https://docs.google.com/document/d/1yjPE69MdT3BhY-HjARFdqkIpqXujORLsKiX6B8GWoLI/edit#heading=h.2ncnl9m75pwv

**Comment by DirtyHippy00** [comment]
There is a sample on how to do this somewhere too with events.

**Comment by ramonmelo** [comment]
Fixed on the next release.

Thanks for your feedback.
