### ISSUE TITLE
BoltEntity state property arrays create massive Editor Overhead

### ISSUE THREAD

**Issue by pippinmole** [BoltEngine/Bolt-Tracker#139]
**To Reproduce**
1. Create a state
2. Add an array of Objects 36 long (for example).
3. Inside the object add 2 or 3 properties
4. Compile assembly
5. Play the scene
6. Select the entity in hierarchy

**Screenshots**
https://gyazo.com/4bd75b5c505ff88e2cdb614566016668

**Desktop (If applicable, please complete the following information):**
 - OS: Windows 10

*It would be nice to have a dropdown for each array.

**Comment by ramonmelo** [comment]
Hello @pippinmole ,

Thanks for your feedback.
We've reviewed the BoltEntity custom inspector and incorporated some performance changes.
And now it's also possible to fold the array properties.

![Screen Shot 2020-06-15 at 17 46 59](https://user-images.githubusercontent.com/873570/84704720-a1703d80-af30-11ea-9267-64965d65f5a1.png)

The changes will be available on the next release.
