### ISSUE TITLE
Behaviour not available in this dispatcher, ignoring call to Remove.

### ISSUE THREAD

**Issue by Zerebokep** [BoltEngine/Bolt-Tracker#14]
This is the code I use:

```
using UnityEngine;
using System.Collections;

[BoltGlobalBehaviour(BoltNetworkModes.Host)]
public class NetworkCallbacks : Bolt.GlobalEventListener {
	
	public override void BoltStartDone () {}

	public override void BoltStartFailed () {}
}
```

For both overrides I receive the warning in the console after quitting the app.

###Configuration
Unity Version: 5.3
Bolt Version: most recent
Operating System: Mac OSX
Network Configuration:

**Comment by herpdederp** [comment]
You can safely ignore this.
