### ISSUE TITLE
Assert fails when starting Bolt if the current scene is from an assetbundle / not in build settings

### ISSUE THREAD

**Issue by djensen19** [BoltEngine/Bolt-Tracker#140]
Bolt fails an assert (with an empty message) if you start Bolt (Server/Client/SinglePlayer) when your active scene isn't in the build. This is typically if the scene is from an asset bundle

**To Reproduce**

Repro project. Just hit play: https://drive.google.com/file/d/1s0IpQWnQuDfa3f15R64Sqk-FeUbfjwlr/view?usp=sharing

1) Have two scenes. Assign one to an asset bundle. Build the bundle. Make sure this scene is not included in the build settings

2) Start the game in the first non-bundled scene

3) At runtime, load the asset bundle, and load into the scene within it (Don't load it additively)

4) Call BoltLauncher.StartSinglePlayer (Or any of the other Start* functions)

**Expected behavior**
Bolt starts normally

**Actual behavior**
Bolt fails an assertion with an empty message. It does not proceed with startup.

Reproduced on both Windows 10 & Android

**Additional context**
- Unity Version: 2019.1.6f1
- Bolt Version: 1.2.9
- Network Configuration: Default

**Comment by ramonmelo** [comment]
@djensen19, 

Could you check again using Bolt 1.2.10 ?

Open again if the issue persists.
