### ISSUE TITLE
Lag Compensation is not work properly

### ISSUE THREAD

**Issue by vladnau89** [BoltEngine/Bolt-Tracker#142]
**Describe the bug**
Lag compensation example from Advanced  Tutorial is not work properly.  The snapshot system does not have snapshot for passed frame yet. it always return previous frame snapshot

**To Reproduce**
1. Go to samples/AdvancedTutorial/scene/Level1
2. Click on "Play As Server" from BoltScenes window
3. Open Bolt.AdvancedTutorial.WeaponRifle.cs
4. Add breakpoint to line 23. 
using (var hits = BoltNetwork.RaycastAll (new Ray (pos, look * Vector3.forward), cmd.ServerFrame)) {
5. Add breakpoint to BoltPhysics.Raycast method
6. Try to shoot from game scene
7. compare the passed frame to BoltPhysics.Raycast  method and last snapshot frame

**Expected behavior**
The snapshot system always have a snapshot for passed frame on playable server at least.

**Actual behavior**
The snapshot system always return previous frame snapshot( it is last snapshot)

**Screenshots**
![Paint 2019-10-01 00 08 41](https://user-images.githubusercontent.com/2057672/65917275-b24b4400-e3df-11e9-99f3-6219fb64ec95.png)

**Desktop (If applicable, please complete the following information):**
 - OS: Windows
 - Version  10

**Additional context**
- Unity Version: 2019.1.10f1
- Bolt Version: 1.2.9

**Comment by ramonmelo** [comment]
Fixed on the next release.

Thanks for your feedback.
