### ISSUE TITLE
Linux Editor can't correctly compile assembly

### ISSUE THREAD

**Issue by syrikaru** [BoltEngine/Bolt-Tracker#143]
**Describe the bug**
As indicated in the title - the "compile assembly" process works without errors, but after building the game, it gives the same error as when you attempt to instantiate an object without having built the assembly to reflect prefab changes. i.e, `Object reference not set to an instance of an object`

**To Reproduce**
1. Use Linux editor
2. Compile Bolt assembly (or don't, same result)
3. Build game
4. Start game
5. Observe Bolt console

**Expected behavior**
It'd work the same as on Windows, where it compiles the assembly and allows the game to instantiate objects.

**Actual behavior**
`Object reference not set to an instance of an object`

**Screenshots**

**Desktop (If applicable, please complete the following information):**
 - OS: Arch Linux
 - Version: latest / up-to-date

**Additional context**
- Unity Version: 2018.4.9f1 LTS
- Bolt Version: 1.2.9
- Network Configuration: Standard "ethernet to router to modem" sort of configuration. No weirdness there.

**Comment by ramonmelo** [comment]
Hello @syrikaru 

Can you share a complete log of your Unity Editor when the exception occurs? 
Have you tested on a different distribution? Or with a different Unity version?

**Comment by ramonmelo** [comment]
Without further information, we are closing the ticket.
