### ISSUE TITLE
False error logged when running as SinglePlayer and ShutdownImmediate is called.

### ISSUE THREAD

**Issue by nlebedenco** [BoltEngine/Bolt-Tracker#144]
Bolt Version 1.2.10
Unity Version: 2019.2

**Actual behavior**
When running in SinglePlayer mode with BoltPoll.AllowImmediateShutdown set to true Bolt incorrectly logs an error on application quit due to UpdSocket.OnEventClose(UdpEvent ev) expecting the platform socket Error property to be null, but udpkit.platform.null.NullSocket.Error returns an empty string instead.

**Expected behavior**
Don't interpret an empty error string as error.
Hint:  Check UpdSocket.OnEventClose(UdpEvent ev) you should do ```if (!string.IsNullOrEmpty(platformSocket.Error))``` and not ```if (platformSocket.Error != null)```

**Comment by ramonmelo** [comment]
Thanks for your feedback!

Fixed on the next release.
