### ISSUE TITLE
Unpredictability caused by overloads of GlobalEventListener.SceneLoadLocalBegin and GlobalEventListener.SceneLoadLocalDone 

### ISSUE THREAD

**Issue by nlebedenco** [BoltEngine/Bolt-Tracker#145]
- Unity Version: 2019.2
- Bolt Version: 1.2.9

Both ```GlobalEventListener.SceneLoadLocalBegin``` and ```GlobalEventListener.SceneLoadLocalDone ``` have overloads with and without ```IProtocolToken```. The problem is that the overload with ```IProtocolToken``` is _not invoked when the token is null_ but the overload **without** ```IProtocolToken``` _is always invoked_. This means that from the handler's standpoint it's impossible to determine if  a scene load does not have a token at all until it's too late. For example, for a client that normally expects a token from the server on scene load there is no way to determine the scene has been loaded without one and do something about it. It cannot simply use ```SceneLoadLocalDone(string scene)``` because there is no way to know if a ```SceneLoadLocalDone(string scene, IProtocolToken token)``` will be invoked right after it or not. 

Expected behaviour:

Always invoke ```SceneLoadLocalBegin(string scene, IProtocolToken token)``` and  ```SceneLoadLocalDone(string scene, IProtocolToken token)``` regardless of the token being null and deprecate the overloads without a token.

NOTE: Same problem applies to 
```SceneLoadRemoteDone(BoltConnection connection)``` 
```SceneLoadRemoteDone(BoltConnection connection, IProtocolToken token)```

**Comment by ramonmelo** [comment]
The Scene related callbacks will be fired in all cases now, even if the IProtocolToken is null.
This is the same behavior that happens with the other `GlobalEventListener` callbacks.

Available on the next release, thanks for your feedback.
