### ISSUE TITLE
BoltNetwork.ServerFrame performance issues

### ISSUE THREAD

**Issue by darvell** [BoltEngine/Bolt-Tracker#149]
**Describe the bug**
`BoltNetwork.ServerTime` performs slowly and fills the GC with a lot of garbage. This is due to the property `BoltCore.server` being used each time and that getter always enumerates the connection linked list. As `BoltNetwork.ServerTime` is expected to be called often throughout a standard game, the enumeration is a bottleneck and ends up Unity calling GC.Alloc/Collect().

**To Reproduce**

Create a bunch of GameObjects with components that call BoltNetwork.ServerTime in the FixedUpdate loop. Run a server instance and run a client instance that connects to  it. Monitor GC usage.

**Expected behavior**
BoltCore.server should be caching the BoltConnection to the server rather than enumerating through the connection list and accessing properties each time, thus leading to less CPU usage and less GC ballooning.

**Actual behavior**
GC can balloon up to 2-10MB in a frame and CPU usage is increased.

**Additional context**
- Unity Version: 2018.4.12f
- Bolt Version: 1.2.9 & 1.2.10 (Pro)
- Network Configuration: Direct connection via bolt Pro

** Solutions **

For other users, I have written a very basic class to act as a way to 'cache' these values and only ever look for the server connection once. This works in server and client mode.

https://gist.github.com/darvell/6d87a66bf764c3d4fb8312c996138038

The real fix should be to change the following in BoltCore:

Original:
```
	public static BoltConnection server
	{
		get
		{
			IEnumerator<BoltConnection> enumerator = BoltCore.connections.GetEnumerator();
			while (enumerator.MoveNext())
			{
				if (enumerator.Current.udpConnection.IsClient)
				{
					return enumerator.Current;
				}
			}
			return null;
		}
	}
```

Optimized:
```
        private BoltConnection _currentServer; // Clear this after BoltCore._udpSocket = null; in BoltCore.BeginShutDown()
	public static BoltConnection server
	{
		get
		{
                       if(_currentServer)
                       {
                           return _currentServer;
                       }
			IEnumerator<BoltConnection> enumerator = BoltCore.connections.GetEnumerator();
			while (enumerator.MoveNext())
			{
				if (enumerator.Current.udpConnection.IsClient)
				{
					return _currentServer = enumerator.Current;
				}
			}
			return null;
		}
	}

**Comment by ramonmelo** [comment]
Thanks for your feedback!

Fixed on the next release.
