### ISSUE TITLE
Add a "Server only" instantiate mode

### ISSUE THREAD

**Issue by Zerebokep** [BoltEngine/Bolt-Tracker#15]
As discussed here: http://forum.photonengine.com/discussion/7727/setting-up-a-true-authoritative-server-environment

It would be great to have a server only instantiate mode to avoid disallowing instantiation on each prefab. This would make the authoritative setup for standalone servers more fail-proof.

**Comment by DirtyHippy00** [comment]
I agree this would be great.

**Comment by fholm** [comment]
This will be in 1.1.0.0 release
