### ISSUE TITLE
Add option in Bolt Scenes to debug start in Single Player

### ISSUE THREAD

**Issue by nlebedenco** [BoltEngine/Bolt-Tracker#150]
### How to reproduce issue

Open Bolt Scenes window with one or more scenes added to the build settings.

### Expected Behavior
Editor Mode should have an option for "Single Player". This option would ignore Clients. The Clients input box should be disabled (or hidden) to indicate the it's not taken into account. 

### Actual behavior
There's currently no option to Debug Start in Single Player

### Configuration
- Unity Version: any
- Bolt Version: 1.2.10
- Operating System: N/A
- Network Configuration: N/A

**Comment by ramonmelo** [comment]
Include on the next release.

Thanks for your feedback.
