### ISSUE TITLE
No indication of SessionConnectFailed cause

### ISSUE THREAD

**Issue by HenryStratton** [BoltEngine/Bolt-Tracker#151]
**Describe the bug**
Joining a session directly via BoltMatchmaking.JoinSession(string , IProtocolToken) when the session is closed, calls the general event SessionConnectFailed but provides no access to information concerning why the connection failed, making it impossible to show appropriate error messages.

Note: Currently looking at a work-around by injecting some logic into LoadBalancingClient.OnOperationResponse which based on logs does have access to the error code of the failure.

**To Reproduce**
1. Run two instances of your project. A and B
2. A starts as server, and creates session "SessionName"
3. A then closes the session with RoomProperties and BoltMatchmaking.CurrentSession.UpdateSession();
4. B starts as client and attempts to join session "SessionName"

**Expected behavior**
SessionConnectFailed should be called either providing the reason for failure, or clients should have access to failure code.

**Actual behavior**
SessionConnectFailed calls with no indication of the failure reason, and with no accessible value available for client to determine why connection failed.

**Desktop (If applicable, please complete the following information):**
 - OS: Windows, Xbox, PS4, Switch, (likely all platforms)

**Additional context**
- Unity Version: 2018.4.14f1
- Bolt Version: 1.2.11RC1
- Network Configuration:

**Comment by ramonmelo** [comment]
Added extra arguments to callbacks: `SessionConnectFailed` and `SessionCreationFailed` with the error reason.
Available on the next release.

Thanks for your feedback.
