### ISSUE TITLE
BoltMatchmaking.JoinSession failed with error "Operation RaiseEvent (253) not called because client is not connected or not ready yet"

### ISSUE THREAD

**Issue by cetester001** [BoltEngine/Bolt-Tracker#152]
### How to reproduce issue
1. After a server session is created, use BoltMatchmaking.JoinSession(string sessionID, IProtocolToken token) to join the specified session.
2. Most of the time, client can connected to the host successfully.
3. But sometimes, it will pop up this error "Operation RaiseEvent (253) not called because client is not connected or not ready yet, client state: Joining".
4. If the error occurred, then the client will not be able to connect to the server until "Room Join failed due to exceeded max time to join".
5. If attempt to JoinSession again after timeout, it will start pinging and can connect to the server.
6. Also, if the error occurred, then the client call BotNetwork.Shutdown, then re-StartClient again, then JoinSession, it will start pinging and can connect to the server.

### Expected Behavior
- If BoltMatchmaking.JoinSession(string sessionID, IProtocolToken token) failed to join the session, it should raise SessionJoinFailed callback before the room join timeout.

### Actual behavior
- Calling BoltMatchmaking.JoinSession(string sessionID, IProtocolToken token) will throw error "Operation RaiseEvent (253) not called because client is not connected or not ready yet, client state: Joining" occasionally, then lead to room join timeout.

### Logs
- Broadcast disabled

- Connecting to a Photon Session

- Changing Connect State: Idle => JoinRoomPending

- Joining to room: 6979

- Local Punch Info: 192.168.1.108:55741|202.186.248.255:55741

- Operation RaiseEvent (253) not called because client is not connected or not ready yet, client state: Joining
UnityEngine.Debug:LogError(Object)
Photon.Realtime.LoadBalancingClient:DebugReturn(DebugLevel, String) (at Assets/Photon/PhotonRealtime/Code/LoadBalancingClient.cs:2042)
Photon.Realtime.LoadBalancingClient:CheckIfOpCanBeSent(Byte, ServerConnection, String) (at Assets/Photon/PhotonRealtime/Code/LoadBalancingClient.cs:1978)
Photon.Realtime.LoadBalancingClient:OpRaiseEvent(Byte, Object, RaiseEventOptions, SendOptions) (at Assets/Photon/PhotonRealtime/Code/LoadBalancingClient.cs:1681)
UdpKit.platform.photon.realtime.PhotonClient:CallOpRaiseEvent(Int32, Byte, String)
UdpKit.platform.photon.puncher.Puncher:HandlePunchInfo(Int32, String)
UdpKit.platform.photon.puncher.Puncher:HandlerPhotonEvent(Byte, Int32, String)
UdpKit.platform.photon.puncher.PunchAPI:HandlerPhotonEvent(Byte, Int32, String)
UdpKit.platform.photon.realtime.PhotonClient:OnEvent(EventData)
ExitGames.Client.Photon.PeerBase:DeserializeMessageAndCallback(StreamBuffer) (at C:/Dev/photon-sdk-dotnet/PhotonDotnet/PeerBase.cs:640)
ExitGames.Client.Photon.EnetPeer:DispatchIncomingCommands() (at C:/Dev/photon-sdk-dotnet/PhotonDotnet/EnetPeer.cs:545)
ExitGames.Client.Photon.PhotonPeer:DispatchIncomingCommands() (at C:/Dev/photon-sdk-dotnet/PhotonDotnet/PhotonPeer.cs:1548)
ExitGames.Client.Photon.PhotonPeer:Service() (at C:/Dev/photon-sdk-dotnet/PhotonDotnet/PhotonPeer.cs:1462)
Photon.Realtime.LoadBalancingClient:Service() (at Assets/Photon/PhotonRealtime/Code/LoadBalancingClient.cs:1030)
UdpKit.platform.photon.realtime.PhotonClient:Update()
UdpKit.platform.photon.PhotonPoller:Update()

- Received PunchInfo from Player 1: 10.148.0.32:58919|35.247.149.246:58919

- Trying to connect via punch through

- Changing Connect State: JoinRoomPending => DirectPending

- Room Join failed due to exceeded max time to join

- Changing Connect State: DirectPending => JoinRoomFailed

- Failed to Join Room.

- Changing Connect State: JoinRoomFailed => Idle

### Configuration
- Unity Version: 2019.2.12f1
- Bolt Version: 1.2.10
- Operating System: Windows 10
- Network Configuration: Wifi

**Comment by ramonmelo** [comment]
Hello @cetester001 ,

Are you able to reproduce your behavior using Photon Bolt 1.2.11?

The "Join Session" process was mostly reworked from the version 1.2.10 to 1.2.11 with extra checks to prevent such cases. We've performed several tests, running local and remote Game servers, without any issues using the latest version.

Thanks for your feedback.

**Comment by cetester001** [comment]
Thanks @ramonmelo ,

It seems like this issue does not occurred after upgrading to v1.2.11, will let you know if there are any problems.

Thank you very much!
