### ISSUE TITLE
Unable to load scenes after disconnecting during a scene load

### ISSUE THREAD

**Issue by ssg-luke** [BoltEngine/Bolt-Tracker#154]
**Describe the bug**
While loading a scene, if Bolt disconnects for whatever reason and is shutdown, then all further attempts to load a scene using BoltNetwork will no longer work. I have debugged this as far as seeing that BoltSceneLoader::Done() is never called for the scene that does eventually load after disconnection/shutdown. This would presumably result in BoltSceneLoader._loadOps.count being stuck as 1 preventing any further BoltNetwork::LoadScene() calls working.

**To Reproduce**
1. Need two scenes in Unity
2. Load the 2nd scene from the 1st scene as a server using BoltNetwork::LoadScene(), force a disconnection and shutdown of Bolt. This may require the 2nd scene that's being loaded to be significantly heavy enough for time to do that.
3. Once the 2nd scene loads, make sure there is code there to kick you back to the 1st scene if !BoltNetwork.IsRunning.
4. Start Bolt back up as a server and try to load the 2nd scene again from the 1st scene. It'll fail.

**Expected behavior**
I would expect that I would be able to load a scene after starting Bolt back up again as a server.

**Actual behavior**
Load scene enqueues the scene to be loaded but nothing will happen.

**Screenshots**
I can provide some if necessary, let me know.

- Windows 10 64-bit
- Unity Version: 2019.2.16f1
- Bolt Version: 1.2.10
- Network Configuration: N/A

**Comment by ramonmelo** [comment]
Fixed on the next release.

Thanks for your feedback.
