### ISSUE TITLE
Calling BoltNetwork.Instantiate() with a protocol token >~1200B results in a silent error.

### ISSUE THREAD

**Issue by tkgszaluga** [BoltEngine/Bolt-Tracker#155]
Calling BoltNetwork.Instantiate() with a protocol token >~1200B appears to succeed (there are no errors logged, no exceptions, etc.), but entity never replicates to connected clients.

**To Reproduce**
1. On the server, create & register a token with more than 1200B of data
2. After starting Bolt, try to instantiate a prefab with Bolt Entity using BoltNetwork.Instantiate()
3. Notice that there are no errors logged, but the entity does not show up on the server or client(s)

**Expected behavior**
Since event data >1200B gets split into multiple packets (according to [this](https://doc.photonengine.com/en-us/realtime/current/troubleshooting/faq#can_i_send_a_huge_message_using_photon_) page), I'd expect protocol tokens to work in a similar way.
Alternatively, an exception should be thrown or an error message logged to the console.

**Actual behavior**
Prefab fails to instantiate without any error.

**Desktop**
 - OS: Windows 10

**Additional context**
- Unity Version: 2019.2.17f1
- Bolt Version: 1.2.11RC1

**Comment by DirtyHippy00** [comment]
This isn't a bug.  That page you link is for Photon and not Bolt.  Bolt doesn't recombine packets.  This is described on the bolt documentation pages here:

https://doc.photonengine.com/en-us/bolt/current/community-wiki/extra-bits/packets

**Comment by tkgszaluga** [comment]
Ah, I see. Thank you for pointing me in the right direction.

Still, logging a message when packet is overflown (especially in debug) while spawning an entity would be very helpful. I expect unreliable events to be dropped silently, but not entity instantiate requests. When this sort of error happens, entity gets spawned on the server but not on any of the clients, with absolutely no indication that something went wrong (leading to things like invisible obstacles, for example). At the same time server needlessly keeps trying to re-serialize the offending token every frame.

**Comment by DirtyHippy00** [comment]
Yes, I agree this should be failed elegantly and logged appropriately.

**Comment by ramonmelo** [comment]
Included warning on the next release.

Thanks for your feedback.
