### ISSUE TITLE
BoltNetwork.CurrentAsyncOperation != null  throw exception

### ISSUE THREAD

**Issue by vladnau89** [BoltEngine/Bolt-Tracker#156]
**Describe the bug**
  code 
 if (BoltNetwork.IsRunning && BoltNetwork.CurrentAsyncOperation != null)
{
}
 throw  exception:

InvalidOperationException: List is empty
BoltSingleList`1[T].VerifyNotEmpty () (at <91e633532a7e4582a260e897276e2d36>:0)
BoltSingleList`1[T].get_first () (at <91e633532a7e4582a260e897276e2d36>:0)
Bolt.SceneManagement.BoltSceneLoader.get_CurrentAsyncOperation () (at <91e633532a7e4582a260e897276e2d36>:0)
BoltInternal.BoltCore.get_currentAsyncOperation () (at <91e633532a7e4582a260e897276e2d36>:0)
BoltNetwork.get_CurrentAsyncOperation () (at <91e633532a7e4582a260e897276e2d36>:0)

**To Reproduce**
1. run PhotonLobby example scene
2. add script to scene with such code 

void FixedUpdate()
{
 if (BoltNetwork.IsRunning && BoltNetwork.CurrentAsyncOperation != null)
{
}

}

3. click @Join to random room@

InvalidOperationException: List is empty
BoltSingleList`1[T].VerifyNotEmpty () (at <91e633532a7e4582a260e897276e2d36>:0)
BoltSingleList`1[T].get_first () (at <91e633532a7e4582a260e897276e2d36>:0)
Bolt.SceneManagement.BoltSceneLoader.get_CurrentAsyncOperation () (at <91e633532a7e4582a260e897276e2d36>:0)
BoltInternal.BoltCore.get_currentAsyncOperation () (at <91e633532a7e4582a260e897276e2d36>:0)
BoltNetwork.get_CurrentAsyncOperation () (at <91e633532a7e4582a260e897276e2d36>:0)

**Expected behavior**
no exception.  

**Actual behavior**
BoltNetwork.CurrentAsyncOperation != null return exception

**Desktop (If applicable, please complete the following information):**
 - OS: windows
 - Version 10

**Additional context**
- Unity Version: 2019.1.10
- Bolt Version: 1.2.10

**Comment by ramonmelo** [comment]
Fixed on the next release.

Thanks for your feedback.
