### ISSUE TITLE
Bolt release mode not compiling

### ISSUE THREAD

**Issue by cetester001** [BoltEngine/Bolt-Tracker#157]
**Describe the bug**
When changing dll mode to Release, compile assembly not compiling anymore.

**To Reproduce**
1. Create a new Unity project.
2. Import Photon Bolt.
3. Complete Bolt wizard setup.
4. Change DLL mode to Release.
5. Try to compile assembly, but not compiling.
6. And console only shows "Searching for prefabs at: Assets".

**Expected behavior**
- Bolt should be able to compile in release mode. (Current workaround is switching back to Debug mode to compile.)

**Configuration**
- Unity Version: 2019.2.18f1
- Bolt Version: 1.2.11b
- Operating System: Windows 10
- Network Configuration: Wifi

**Comment by ramonmelo** [comment]
Hello @cetester001 ,

Have you checked if your changes in the Assets, Scenes or Prefabs are compiled in Release mode, even if there are no logs indicating this?

**Comment by cetester001** [comment]
Hello @ramonmelo , thanks for your reply!
I just tested in release mode, create a new event then try compile, but still not working, the new event cannot be found.

**Comment by ramonmelo** [comment]
Fixed on the next release.

Thanks for your feedback.

**Comment by cetester001** [comment]
Thank you very much!
