### ISSUE TITLE
Bolt cannot be started if invoking ShutdownImmediate before BoltStartDone

### ISSUE THREAD

**Issue by cetester001** [BoltEngine/Bolt-Tracker#158]
**Describe the bug**
If invoking ShutdownImmediate before the BoltStartDone event occurred, StartClient or StartServer will not working anymore.

**To Reproduce**
1. Try to invoke Bolt.StartClient or Bolt.StartServer.
2. Then invoke BoltNetwork.ShutdownImmediate() before the BoltStartDone event occurred.
3. Cannot StartClient or StartServer anymore.
4. The current workaround is to manually delete a BoltControl object in the scene, then it can start again.

**Expected behavior**
Tested with Bolt version 1.2.10b, Bolt can start again if invoking ShutdownImmediate() before the BoltStartDone event occurred.

**Additional context**
- Unity Version: 2019.2.18f1
- Bolt Version: 1.2.11b
- Operating System: Windows 10
- Network Configuration: Wifi

**Comment by ramonmelo** [comment]
Fixed on the next release.

Thanks for your feedback.

**Comment by cetester001** [comment]
Thank you very much!
