### ISSUE TITLE
Enhancement: Log when AppID hasn’t been set

### ISSUE THREAD

**Issue by pippinmole** [BoltEngine/Bolt-Tracker#160]
### How to reproduce issue
1. Create a blank bolt project
2. Compile and run with no AppID

### Expected Behaviour
Should let you know your AppID hasn’t been set - as methods such as BoltStartDone do not get run, and no errors/logs get thrown

### Actual behaviour
Bolt silently runs with nothing happening

### Configuration
- Unity Version: 2019.3.3f
- Bolt Version: latest
- Operating System: Windows 10

**Comment by ramonmelo** [comment]
Added extra checks when initializing Bolt.
Available on the next release.

Thanks for your feedback.
