### ISSUE TITLE
Bolt Release Mode not Compiling Assets

### ISSUE THREAD

**Issue by pippinmole** [BoltEngine/Bolt-Tracker#161]
**Describe the bug**
When you switch to Release mode, and try to compile it won't run through the entire bolt compilation process.

**To Reproduce**
1. Switch to Release mode
2. Add a new property to a state
3. Bolt > Compile Assembly
4. Try the same for Debug mode and notice how it works

**Expected behavior**
New property should be added to the Interface

**Actual behavior**
The interface stays the same :(

**Screenshots**
https://cdn.discordapp.com/attachments/174932278579822592/685619954879561776/unknown.png
Bolt > Compile Assets for Debug Mode (Working)

https://cdn.discordapp.com/attachments/174932278579822592/685620201252716600/unknown.png
Bolt > Compile Assets for Release Mode (Not working)

**Desktop (If applicable, please complete the following information):**
 - OS: Windows 10
 - Version 1909

**Additional context**
- Unity Version: 2019.3.3f1
- Bolt Version: v1.2.11b

**Comment by herpdederp** [comment]
https://github.com/BoltEngine/Bolt-Tracker/issues/157
