### ISSUE TITLE
[Enhancement] When the App ID is null/empty, nothing is logged, however sessions do not show

### ISSUE THREAD

**Issue by pippinmole** [BoltEngine/Bolt-Tracker#164]
**Describe the bug**
Should at least log if the appid isn't set when you play the game

**To Reproduce**
1. Build a game with no app id set
2. Try to find a hosted session

**Expected behavior**
Should be notified app id isnt set

**Actual behavior**
Nothing is logged

**Desktop (If applicable, please complete the following information):**
 - OS: Windows 10

**Additional context**
- Unity Version: 2019.3.3f1
- Bolt Version: v1.2.12

**Comment by ramonmelo** [comment]
Hello @pippinmole , 

Just to confirm, are you testing like this? [Video Link](https://youtu.be/Y4e_jezuN54)
We are not able to reproduce the behavior you described.

**Comment by pippinmole** [comment]
Does it have anything to do with being in release mode?

**Comment by ramonmelo** [comment]
Hello,

Yes, most of the logs are disabled in Release mode, including this one, that is one-fire message.
Also, if you have updated Bolt to 1.2.12, it starts in Debug mode, so you should have seen the log like is shown in the video.
