### ISSUE TITLE
New unity Input system not supported?

### ISSUE THREAD

**Issue by alanaasmaa** [BoltEngine/Bolt-Tracker#167]
**Describe the bug**
I followed the documents and created my game but I'm using new input system.

**To Reproduce**
1. Go to "Project Settings"
2. "Player" and "Other Settings"
3. Set Active Input Handling to Input System Package (new)
4. Build the game and you receive an errors in console.

**Expected behavior**
I except no error.

**Actual behavior**
I recive an error, but everything runs fine.

```
InvalidOperationException: You are trying to read Input using the UnityEngine.Input class, but you have switched active Input handling to Input System package in Player Settings.
UnityEngine.Input.GetKeyDown (UnityEngine.KeyCode key) (at <2db13ba0d52343228aa9892c408fb49a>:0)
Bolt.DebugInfo.OnGUI () (at <6cbc9c6b8b9249ed89833fc014dfdb8e>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/12788337/82339748-0ea6b680-99f7-11ea-83c6-7cf653d2a1df.png)

**Desktop (If applicable, please complete the following information):**
 - Device: PC
 - OS: : Windows 10

**Additional context**
- Unity Version: Unity 2019.3.14f1
- Bolt Version: v1.2.12
- Network Configuration: [config]

**Comment by herpdederp** [comment]
Workaround until next release: Disable "Show Debug Info" in Bolt Settings or set Input Modes as "Both" in Unity Player Settings.

**Comment by ramonmelo** [comment]
Fixed on the next release.

Thanks for your feedback.
