### ISSUE TITLE
Error in Bolt online documentation  

### ISSUE THREAD

**Issue by viliamvolosv** [BoltEngine/Bolt-Tracker#169]
https://doc.photonengine.com/en-us/bolt/current/reference/boltentity/

What About Normal Proxies, Which Are Not The Controller?
On normal proxies, which are not in direct control of the entity and are not the owner of the entity, **the only callback which executes is SimulateProxy()**, neither SimulateController() or ExecuteCommand() runs on them.

IEntityBehaviour - entity  dose not have **SimulateProxy()**

**Comment by ramonmelo** [comment]
Hello @viliamvolosv ,

That page was already updated with new information about the Bolt Entity, it will be available soon.
Thanks for your feedback.
