### ISSUE TITLE
Render Transform not working

### ISSUE THREAD

**Issue by fdreher** [BoltEngine/Bolt-Tracker#17]
https://doc.photonengine.com/en/bolt/current/in-depth/temporal-anti-aliasing describes how to use a render transform to smooth the effects of the difference between frame rate and simulation rate. Unfortunately this is not working, because the render transform is simply not being used by Bolt.

Possible fix: https://github.com/fdreher/bolt/commit/f5e1be4de30d8a55d4d6061c261f9952061341f3

**Comment by herpdederp** [comment]
Fixed in 0.4.3.17
