### ISSUE TITLE
`BoltNetwork.RemoveGlobalEventCallback` does not remove callbacks

### ISSUE THREAD

**Issue by heilhead** [BoltEngine/Bolt-Tracker#170]
**Describe the bug**
Apologies for sticking my nose into your code, but I'm having a problem where `BoltNetwork.RemoveGlobalEventCallback<T>(Action<T> callback)` would not find the callback and throw a warning `Could not find delegate registered as callback`.

I believe the problem is in the `if (!this._callbacks.TryGetValue(typeof (T), out callbackWrapperList))` line of the following function (`EventDispatcher.Remove`):
```csharp
    public void Remove<T>(Action<T> callback) where T : Event
    {
      List<EventDispatcher.CallbackWrapper> callbackWrapperList;
      if (!this._callbacks.TryGetValue(typeof (T), out callbackWrapperList))
      {
        for (int index = 0; index < callbackWrapperList.Count; ++index)
        {
          if ((Delegate) callbackWrapperList[index].Original == (Delegate) callback)
          {
            callbackWrapperList.RemoveAt(index);
            return;
          }
        }
      }
      BoltLog.Warn("Could not find delegate registered as callback");
    }
```

**To Reproduce**
```csharp
BoltNetwork.AddGlobalEventCallback<ReliableStateSyncEvent>(OnEvent);

// The following call throws a warning and does not remove the callback:
BoltNetwork.RemoveGlobalEventCallback<ReliableStateSyncEvent>(OnEvent);
```

**Expected behavior**
The callback would be removed.

**Actual behavior**
The warning is thrown, the callback is not removed.

**Screenshots**
Not applicable.

**Desktop (If applicable, please complete the following information):**
 - OS: Windows 10
 - Version: 10.0.19041

**Smartphone (If applicable, please complete the following information):**
 - Device: -
 - OS: -

**Additional context**
- Unity Version: 2019.4.1f1
- Bolt Version: 1.2.12
- Network Configuration: -

**Comment by ramonmelo** [comment]
Hello @heilhead ,

Fixed on the next release.

Thanks for your feedback.
