### ISSUE TITLE
UdpSessionError

### ISSUE THREAD

**Issue by yessGlory17** [BoltEngine/Bolt-Tracker#171]
There is a pointless type mismatch problem here.
 public override void SessionListUpdated(Map<Guid, UdpSession> sessionList)
    {
        foreach(var session in sessionList)
        {
            
            UdpSession photonSession = session.Value as UdpSession;
           
            if(photonSession.Source == UdpSessionSource.Photon)
            {
                BoltNetwork.Connect(photonSession);
            }
        }
    }

When I try to fix the type mismatch, it does not establish the correct connection while working this time.

public override void SessionListUpdated(Map<Guid, UdpSession> sessionList)
    {
        foreach(var session in sessionList)
        {
            
            UdpSession photonSession = session.Value as UdpSession;
           
            if(photonSession.Source == UdpSessionSource.Photon)
            {
                BoltNetwork.Connect(Convert.ToUInt16(photonSession));
            }
        }
    }

![phproblem](https://user-images.githubusercontent.com/52113663/88383946-28c49280-cdb4-11ea-9a7d-d48bb2b780ab.PNG)
![phproblem2](https://user-images.githubusercontent.com/52113663/88383948-295d2900-cdb4-11ea-9978-c3da744bccc2.PNG)

**Comment by ramonmelo** [comment]
Hello @yessGlory17 ,

Please follow the Getting Started documentation on our site: [https://doc.photonengine.com/en-us/bolt/current/demos-and-tutorials/bolt-basics/bolt-102-getting-started](https://doc.photonengine.com/en-us/bolt/current/demos-and-tutorials/bolt-basics/bolt-102-getting-started).
It shows the basics of how to start using Bolt.

In order to join a session, you need to use the `BoltMatchmaking` API, more specifically the `BoltMatchmaking.JoinSession(photonSession)` method.

Have a nice day.

**Comment by yessGlory17** [comment]
Sir, this is not work!
![phproblem3](https://user-images.githubusercontent.com/52113663/88387399-0aae6080-cdbb-11ea-920b-6995dd29d44f.PNG)
![phproblem4](https://user-images.githubusercontent.com/52113663/88387403-0bdf8d80-cdbb-11ea-9f7d-32085683eb57.PNG)

**Comment by ramonmelo** [comment]
Hello @yessGlory17 ,

Please, follow the Getting Started tutorial: https://doc.photonengine.com/en-us/bolt/current/demos-and-tutorials/bolt-basics/bolt-102-getting-started

Also, the method can receive a `UdpSession` directly (`BoltMatchmaking.JoinSession(photonSession);`).
The param you are passing (`photonSession.Id`) is a Unique GUID created randomly for each session, and it does not represent the Session Name.
