### ISSUE TITLE
Typo in BoltNetwork.Entities description

### ISSUE THREAD

**Issue by alkboda** [BoltEngine/Bolt-Tracker#173]
Typo is made in [API documentation](https://doc-api.photonengine.com/en/bolt/current/class_bolt_network.html#a532a94e2ec5699589400785822b1cf0f) and in [bolt assembly](https://drive.google.com/uc?id=1s2eoIC1apx0esSZwRtP0X2b4XKy4NQ7i).
Summary duplicates the summary of BoltNetwork.Frame property

**Comment by ramonmelo** [comment]
Hello @alkboda ,

Documentation updated.

Thanks for your feedback.
