### ISSUE TITLE
Photon realtime returns what I would think should be an error as a Warning in editor output

### ISSUE THREAD

**Issue by GetLitGames** [BoltEngine/Bolt-Tracker#178]
**Describe the bug**
Enter an invalid App Id in Bolt Settings. All that is logged are two Warnings and no Errors but Photon/Bolt fails to start.

**To Reproduce**
Run your app/game. BoltStartDone never happens. If you have Warnings in the console turned off, you don't know why because you see no errors.

**Expected behavior**
Bolt or Photon should throw an Error not a Warning. An exception and an invalid App Id completely stops your app/game from continuing and Bolt fails to start.

**Actual behavior**
You only see two Warnings in the log output:
**Exception while running command Bolt.ControlCommandStart**
and then
**System.ArgumentException: Please, inform a valid Photon App ID**

Personally, an exception thrown should be probably be logged as an Error but regardless, the second "warning" stops your app/game completely since Bolt/Photon did not startup and should be logged as an Error.

**Screenshots**
![image](https://user-images.githubusercontent.com/65694602/97797520-cd444500-1beb-11eb-8126-f57a7614b5b5.png)

**Desktop (If applicable, please complete the following information):**
Any

**Smartphone (If applicable, please complete the following information):**
Any

**Additional context**
- Unity Version: 2019.4.4f1
- Bolt Version: 1.2.12

**Comment by ramonmelo** [comment]
Updated to show an Error on the next release.

Thanks for your feedback.
