### ISSUE TITLE
Bolt Connection times out earlier than expected

### ISSUE THREAD

**Issue by sa-martinlundgren** [BoltEngine/Bolt-Tracker#185]
**Describe the bug**
Bolt disconnect earlier than expected when app is not focused on Oculus Quest.

**To Reproduce**
1. Check Bolt Settings in Unity, note how many milliseconds the 'Timeout' field is set to (e.g. 60000 ms)
2. Start a game with Host and Client on Oculus Quest
3. Have the Client take of the headset
4. Note that Host tends to disconnect the Client well before the Timeout is hit, usually 10-30 seconds in

**Expected behavior**
I expected the connection to only timeout after we reach the timelimit set by the 'Timeout' field in Bolt Settings.

**Actual behavior**
Host disconnect the Clients way sooner, usually 10-30 seconds in.

**Desktop (If applicable, please complete the following information):**
 - Device: Meta Quest 2
 - OS: 46

**Additional context**
- Unity Version: 2020.3.19f1
- Bolt Version: 1.2.14a
- Network Configuration:
    framesPerSecond: 36
    packetSize: 1200
    packetMaxEventSize: 512
    packetStreamSize: 4096
    maxEntityPriority: 65536
    maxPropertyPriority: 2048
    scopeMode: 0
    logTargets: 3
    disableDejitterBuffer: 0
    clientSendRate: 2
    clientDejitterDelay: 6
    clientDejitterDelayMin: 3
    clientDejitterDelayMax: 9
    serverSendRate: 2
    serverDejitterDelay: 6
    serverDejitterDelayMin: 3
    serverDejitterDelayMax: 9
    serverConnectionLimit: 3
    serverConnectionAcceptMode: 1
    commandQueueSize: 60
    commandRedundancy: 6
    commandPingMultiplier: 1.25
    useNetworkSimulation: 0
    simulatedLoss: 0.02
    simulatedPingMean: 200
    simulatedPingJitter: 10
    simulatedRandomFunction: 0
    connectionTimeout: 120000
    connectionRequestTimeout: 1000
    connectionRequestAttempts: 10
    disableAutoSceneLoading: 0
    EnableIPv6: 0
    
**Other notes:**
This issue is causing us concern, because we think it might cause us to fail [VRC.Quest.Functional.11](https://developer.oculus.com/resources/vrc-quest-functional-11/), which is required to ship on the Meta Quest Store. We're looking for advice on how to deal with this situation.
 
There is some notes [here](https://doc.photonengine.com/en-us/realtime/current/troubleshooting/known-issues#running_in_background) from another Photon product which indicates that this is a known issue.

Is the only workaround to reconnect to the game when the player puts the headset on again, or is there anything else we can do?

**Comment by ramonmelo** [comment]
@sa-martinlundgren 

Please, send us an email to `developer@photonengine.com` with any extra info you have.

We will close this ticket and wait for your email.

--
Ramon Melo
Photon Bolt Team
