### ISSUE TITLE
If AssignControl to same controller multiple times, misleading error message is displayed.

### ISSUE THREAD

**Issue by JayJangArchiact** [BoltEngine/Bolt-Tracker#19]
### How to reproduce issue
1. Have AssignControl to be called every frame
2. Switch controls to a client
3. Have client send command to server every frame
### Expected Behavior

Tell us what should happen
Either 
a) Error "Cannot assign control to controller. Check param != controller before calling AssignControl"
b) No error and works correctly
### Actual behavior

Tell us what happens instead

Spams " Input queue for --- is full " error, and essentially freezes sync on that object on client. 
### Configuration

Unity Version: 5.4.0f3
Bolt Version 0.4.3.15
Operating System: Windows 10
Network Configuration:

**Comment by JayJangArchiact** [comment]
I think internally if you are assigning controller somehow stops Input Queue from submitting and that error is displayed.

Regardless, that error does not help solving the core problem for the user.

**Comment by ramonmelo** [comment]
Hello,

Why would you assign the control of an entity every frame?

**Comment by ramonmelo** [comment]
Thanks for your feedback!

Fixed on the next release.
