### ISSUE TITLE
StreamData started callback

### ISSUE THREAD

**Issue by herpdederp** [BoltEngine/Bolt-Tracker#2]
An override like StreamDataReceived but at the beginning of the stream, because now we only know we got data from the server when we already have it all

**Comment by Qmaks** [comment]
And Please add StreamDataProgress Callback.
To know on clients progress value to draw progressbars

**Comment by ramonmelo** [comment]
Added new `GlobalEventListener` callbacks `StreamDataStarted` and `StreamDataProgress` on the next release.

Thanks for your feedback.
