### ISSUE TITLE
Compile assembly fails on Unity 5.4.0f3 on OS X

### ISSUE THREAD

**Issue by richcollins** [BoltEngine/Bolt-Tracker#20]
###How to reproduce issue
1. Compile the assembly using 0.4.3.16 on Unity 5.4.0f3 (OS X 10.11.6)

###Expected Behavior
Assembly should compile and update project.bytes

###Actual behavior
Win32Exception: ApplicationName='/Applications/Unity/Unity.app/Contents/Frameworks/MonoBleedingEdge/bin/mono', CommandLine='"/Applications/Unity/Unity.app/Contents/Frameworks/MonoBleedingEdge/lib/mono/4.5/mcs.exe"

###Configuration
Unity Version: 5.4.0.f3
Bolt Version: 0.4.3.16
Operating System:OS X 10.11.6
Network Configuration:

**Comment by herpdederp** [comment]
if you want to fix the OSX 5.4 Bolt issue before the next release

cd /Applications/Unity/Unity.app/Contents/Frameworks
ln -s ../MonoBleedingEdge/ MonoBleedingEdge
ln -s ../Managed Managed

**Comment by herpdederp** [comment]
Fixed in 0.4.3.17
