### ISSUE TITLE
SessionListUpdated called twice

### ISSUE THREAD

**Issue by richcollins** [BoltEngine/Bolt-Tracker#22]
### How to reproduce issue
1. call Bolt.Zeus.RequestSessionList() for a zeus connection that has 1 or more sessions
### Expected Behavior

SessionListUpdated should be called once, with the list of existing sessions
### Actual behavior

SessionListUpdated is called twice.  The first time sessionList is empty.  The second time (around 0.7s later) the sessionList has the expected sessions
### Configuration

Unity Version: 5.4.0f3
Bolt Version 0.4.3.17 RELEASE
Operating System: OS X
Network Configuration: N/A

**Comment by 8BitRick** [comment]
This is just weird and requires special code to ignore empty sessions. I find myself finding random bugs with state because of this extra complexity. Fix would be much appreciated. :)

**Comment by richcollins** [comment]
I've discovered another case where there is no workaround.  As stated before, RequestSessionList calls SessionListUpdated twice, once with an empty session list and once with the actual session list.  However, if you call it again before the second call to SessionListUpdated, the second call is never made.  This makes it impossible to use a timer to poll for a session because it always returns 0 if the timer fires before the second SessionListUpdated call.

**Comment by herpdederp** [comment]
Please use the new Photon Cloud integration instead
