### ISSUE TITLE
Can't connect to Zeus after BoltLauncher.StartSinglePlayer() followed by BoltLauncher.Shutdown()

### ISSUE THREAD

**Issue by richcollins** [BoltEngine/Bolt-Tracker#23]
###How to reproduce issue
1. BoltLauncher.StartSinglePlayer()
2. In BoltStartDone: BoltLauncher.Shutdown();
3. After Shutdown Completes: BoltLauncher.StartClient();
4. In BoltStartDone: Bolt.Zeus.Connect(UdpKit.UdpEndPoint.Parse("159.8.0.207:24000"));

###Expected Behavior
ZeusConnected or ZeusConnectFailed called

###Actual behavior
neither ZeusConnected or ZeusConnectFailed called (silent failure)

###Configuration
Unity Version: 5.4.1f1
Bolt Version: 4.3.18
Operating System: OS X 10.11.16
Network Configuration: 
[BoltTest.cs.zip](https://github.com/BoltEngine/Bolt-Tracker/files/573549/BoltTest.cs.zip)

**Comment by richcollins** [comment]
Not sure if its related, but I also see this when shutting down single player:

11/05/2016 16:30:59: Failed to shutdown socket, platform error: 
UnityEngine.Debug:Log(Object)
BoltCore:<BeginShutdown>b__1b(UInt32, String)
UdpKit.UdpLog:Write(UInt32, String)
UdpKit.UdpLog:Error(String, Object[])
UdpKit.UdpSocket:OnEventClose(UdpEvent)
UdpKit.UdpSocket:ProcessInternalEvents()
UdpKit.UdpSocket:NetworkLoop()

**Comment by herpdederp** [comment]
Please use StartServer instead, it is identical to StartSinglePlayer. StartSinglePlayer is for offline only.
