### ISSUE TITLE
Bolt.RaycastAll hit.distance is incorrect when Transform of object scaled

### ISSUE THREAD

**Issue by charlesmccann** [BoltEngine/Bolt-Tracker#25]
###How to reproduce issue
Details and code to be used in Bolt sample code (0.4.3.19).  
Add Cube with Unity Collider, Bolt HitboxBody and Bolt Hitbox.  Scale Transform size up.
https://tagmycode.com/snippet/6149/unity-photon-bolt-raycast-distances#.WGp4CvkrKUk 

###Expected Behavior
Bolt hit.distance should be about the same distance as the unity collider hit.distance

###Actual behavior
Hit.Distance calculations are off by a factor of the Transform scaling.

###Configuration
Unity Version:  5.5.0f3
Bolt Version:  0.4.3.19
Operating System:  Windows 10
Network Configuration:

**Comment by DirtyHippy00** [comment]
To clarify, this is because scaling the transform of anything containing a bolt hitbox borks everything up.  However, it does seem like the gizmo for the hitbox is scaling (which it shouldn't if the scale of the transform doesn't affect it).  In any case, would be great if it could be fixed.

**Comment by ramonmelo** [comment]
Fixed on the next release.
