### ISSUE TITLE
SetTransforms (transform,null) no longer works

### ISSUE THREAD

**Issue by DirtyHippy00** [BoltEngine/Bolt-Tracker#26]
###How to reproduce issue
1.  Call state.SetTransforms (transform,null) to stop syncing transforms
2. crashy crashy
3.

###Expected Behavior
Should clear out the simulate and stop syncing transforms.

###Actual behavior
Tries to access the simulate member and fails (since it is null)

This was fixed in 4.3.8 (fholm fixed it because I had filed a bug for it) and the fixed behaviour was reverted in 4.3.14.

**Comment by DirtyHippy00** [comment]
Note: the working version that fholm was using is still there, but commented out.

**Comment by herpdederp** [comment]
Fixed in 0.4.4.1
