### ISSUE TITLE
sceneObjectDestroyOnDetach is broken

### ISSUE THREAD

**Issue by Zerebokep** [BoltEngine/Bolt-Tracker#27]
###How to reproduce issue
1. set sceneObjectDestroyOnDetach to false either through the inspector debug mode or by script.
2. use BoltNetwork.Detach(gameObject) on the server app

###Expected Behavior
The game object shouldn't get destroyed.

###Actual behavior
The game object gets destroyed.

###Configuration
Unity Version: 5.3
Bolt Version: most recent
Operating System: mac os sierra

**Comment by ramonmelo** [comment]
Hello,

Do you have sample project demonstrating this behavior ?

**Comment by ramonmelo** [comment]
Fixed on the next release.

Fix commit: https://github.com/BoltEngine/bolt-internal/commit/caff56915abbd8d99af5859054e018e7e68c996c
