### ISSUE TITLE
BoltNetwork.RemoveGlobalEventCallback in OnDestroy broken

### ISSUE THREAD

**Issue by equusligneus** [BoltEngine/Bolt-Tracker#28]
###How to reproduce issue
1. Start Bolt Server
2. Change to another Scene ('Scene2')
3. Subscribe to a BoltEvent ('TestEvent') using BoltNetwork.AddGlobalEventCallback (e.g. during Start)
4. Send 'TestEvent' to yourself
5. Log receiving the 'TestEvent'
6. Reload 'Scene2'
7. During OnDestroy unsubscribe using BoltNetwork.RemoveGlobalEventCallback

###Expected Behavior
RemoveGlobalEventCallback removes the old event listener
-> 1 'Received'-Log per Scene load

###Actual behavior
RemoveGlobalEventCallback does not remove the old listener (no errors)
-> 2 'Received'-Logs the second time the Scene is loaded (a total of 3 together with the log of the first time)
-> 3 'Received'-Logs the third time and so on

###Configuration
Unity Version: 5.5.0f3
Bolt Version: 0.4.3.18
Operating System: Win 10 64bit
Network Configuration: -

**Comment by herpdederp** [comment]
I do not follow "reload scene 2", we don't have support for this in BoltNetwork.LoadScene etc.
