### ISSUE TITLE
Need to translate 6 [(null)] into winsock error

### ISSUE THREAD

**Issue by Erdroy** [BoltEngine/Bolt-Tracker#30]
###How to reproduce issue
1. Cannot reproduce on other machines, some error handling needed

###Expected Behavior
Server should accept connection request.

###Actual behavior
Cannot connect to server, no any connection track is on the dedicated server, log:
UdpKit.UdpSocket
2/7/2017 1:58:32 PM: socket closed
WSAIoctl: Need to translate 6 [(null)] into winsock error

this is happening on ***only one single*** machine.
Probably caused by Mono.

###Configuration
Unity Version: 5.5.0p3
Bolt Version: 0.4.3.19
Operating System: OSX 64bit
Network Configuration: --

**Comment by herpdederp** [comment]
Please reopen if you have repro
