### ISSUE TITLE
 Vector3 BoltHitbox.hitboxCenter example is wrong

### ISSUE THREAD

**Issue by msmsmsm** [BoltEngine/Bolt-Tracker#31]
The example for hiBoxCenter is misleading as it will not get a vector to the head of the target entity as the center of a BoltHitboxBody is in local coordinates, not world coordinates.

Eample: Getting a vector that points from the player's weapon to the head of a target entity.

   1 Vector3 GetHeadshotVector(BoltEntity target, IWeapon currentWeapon) {
    2   BoltHitboxBody body = target.GetComponent<BoltHitboxBody%gt();
    3   BoltHitbox head = body.hitboxes[0];
    4
    5   foreach(BoltHitbox hitbox in body.hitboxes) {
    6     if(hitbox.hitboxType == BoltHitboxType.Head) {
    7       head = hitbox;
    8     }
    9   }
   10
   11   return head.hitboxCenter - currentWeapon.fireOrigin;
   12 }

**Comment by herpdederp** [comment]
I believe the sample assume both are local. Before the sample it says "Center of the hitbox in local coordinates" http://doc-api.photonengine.com/en/BOLT/current/class_bolt_hitbox.html#a67d64787003b0ad37d9cd70a7f9ee53d
