### ISSUE TITLE
Photon Cloud - BoltNetwork.Connect token is null on server callback when direct connect, not null when relay

### ISSUE THREAD

**Issue by DMeville** [BoltEngine/Bolt-Tracker#32]
###How to reproduce issue
1. Download project at the bottom (Bolt 1.0.0.4 from asset store with extra logging and large assets removed)
2. Build one player, start it as server.
3. Open the PhotonMenu scene, play the editor, connect to the server.
4. Make note of the green logs in the bolt console, they show what kind of connection is made (relay, or direct)
5. If direct connection is made, on the server ConnectRequest token is null
6. If relay is used, on the server ConnectRequest token is not null

###Additional Info
BoltPhotonInit.cs is where the token is created and passed with BoltNetwork.Connect
testCallbacks.cs is where the callbacks are, with logging and comments.  

###Expected Behavior
Token received from the Bolt callback ConnectRequest should not be null, it should be the token sent from the client in BoltNetwork.Connect.

###Actual behavior
When Photon makes a direct connection to the server the token in ConnectRequest is null.  
When Photon fails to make a direct connection and uses relay the token in Connect request is not null.

Video reproduction here: https://www.youtube.com/watch?v=JXYpRIaOVwg

###Configuration
Unity Version: 5.5.2f1
Bolt Version: 1.0.0.4
Operating System: Tested both Windows 10 and  OSX 10.11.5
Network Configuration: --

Github won't let me upload a zip for some reason, so the project can be found on google drive here: https://drive.google.com/open?id=0B7k_kAQmaYNVeDhDb3pWZ1ZkdUE

**Comment by DMeville** [comment]
PhotonPoller.JoinSessionRoutine uses BoltNetwork.Connect(zeusSession) without a token, change this to                     BoltNetwork.Connect(zeusSession, token as Bolt.IProtocolToken);

**Comment by herpdederp** [comment]
Fixed in 1.0.0.5
