### ISSUE TITLE
Photon Cloud - Inconsistent connection results, sometimes direct, sometimes relay

### ISSUE THREAD

**Issue by DMeville** [BoltEngine/Bolt-Tracker#33]
###How to reproduce issue
1.  Download Bolt 1.0.0.4 from asset store.
2.  Add PhotonMenu and Level1 scenes to the build settings.  
3. Build one player, play it, start server and load map
4. Open the PhotonMenu scene, play the editor.
5. Connect to the server and take note of the connection status in the bolt console.  If a direct connection is made you will see "Changing Connect State: Direct Pending => Direct Success", if relay is used you will see "Changing Connect State: Relay Pending => Relay Success"
6. Repeat step 5.  Repeating multiple times as needed, results in different connections being made.  Sometimes relay is used, sometime direct connection is used.  See the video below to see this happen.

https://www.youtube.com/watch?v=Sf7dRU4WEjA

###Expected Behavior
If a direct connection can be made, it should always be used.

###Actual behavior
Sometimes a direct connection is made, sometimes it uses relay, changing for no apparent reason.

###Configuration
Unity Version: 5.5.2f1
Bolt Version: 1.0.0.4
Operating System: Windows 10 and OSX 10.11.5
Network Configuration: --

**Comment by DMeville** [comment]
In the hopes that I can speed this along and get it fixed sooner, I've been trying nail down what's going on, hoping it's not internal and I can fix it by editing PhotonPoller myself I've sort of narrowed down what is happening. 

 The issue seems to be that in the JoinSessionRoutine, the BoltNetwork.SessionList.TryFind(s._socketPeerId, out zeusSession) _sometimes_ fails and _sometimes_ it works.  Thinking maybe the problem was the call to Zeus.RequestSessionList not returning results immediately.  I'm not sure exactly what's happening, but it seems sometimes after calling Zeus.RequestSessionList, the SessionListUpdated callback will be triggered twice.  The first time there is only one session (as I'd expect, there is only one server running) with the session.Source show as "Photon", the second time there are two sessions, the "Photon" session, and a "Zeus" session.

So for _some_ reason, _sometimes_ the second SessionListUpdated call takes longer to trigger (or doesn't ever get triggered?) and so it can't find the "Zeus" session it's looking for.  Seems like sometimes the delay it takes LoadBalancerClient.OpJoinRoom to complete is enough waiting time, but not always.

If you move the Zeus.RequestSessionList() from where it is in the PhotonPoller.JoinSessionRoutine to between the if(_lbClient.State != ClientState.Joined) block and if(_config.UsePunchthrough), Direct connect will fail every time.  (Or at least every time I tested, and I actually tested it 50 times..).  

Further, if you add a yield return new WaitForSeconds(5f) AFTER the call to Zeus.RequestSessionList() (in it's new location) it seems to work more often (only tested this 25 times, every time a direct connection was made, will test this more and on a few different networks).  It's not ideal, as this means players have to wait an extra few seconds even if they don't need to (in the off case that the sessions are returned sooner), but it's better than using relay when a direct connection can be made.  A proper solution would be great, but it doesn't look like there's enough exposed for me to keep digging.  

I'm assuming Zeus.RequestSessionList() fetches the list from zeus/photon servers, so I'm not sure 5 seconds of waiting will be enough in cases where a player has a worse connection speed, or in whatever situation that would result in Zeus.RequestSessionList taking longer than 5 seconds to return valid sessions, but I'm not sure what else to try at this point.

It seems like it's somewhat related to this issue: https://github.com/BoltEngine/Bolt-Tracker/issues/22

**Comment by DMeville** [comment]
Further testing.  Instead of testing with both client and host on the same computer, or with client and host on different computers on the same LAN, I had someone run the host in Western USA and I would connect over the internet from Central Canada.

The changes outlined in the last comment of moving Zeus.RequestSessionList, and adding a new WaitForSeconds(5f) that allowed for DirectConnect to succeed 100% of the time while on LAN, unfortunately did not also work while testing over the internet.

Testing the "lan" working code over the internet results in not even getting to the point where the ConnectState is changed to DirectPending, it just logs "Writing: Punch" constantly for a while and then fails silently without going further, doesn't even report something failed.

Removing the WaitForSeconds(5f) stops this from happening and allows a connection, but 100% of the time Relay is being used, as I discovered in the last comment.

Eager to get this working reliably, but unsure of what to try next.
Video: https://www.youtube.com/watch?v=r2Jg6N85Qgg

**Comment by DMeville** [comment]
The proposed fix seems to work consistently when a standalone player is used for both the client and host.  The above issue only seems to happen while testing with the client or host using the Unity editor, but more testing is needed to confirm this is the case.

**Comment by herpdederp** [comment]
Fixed in 1.0.0.5
