### ISSUE TITLE
Support for Physics.Simulate in Bolt

### ISSUE THREAD

**Issue by heretique** [BoltEngine/Bolt-Tracker#34]
Hi, 
I was wondering lately how hard it is to add support for Physics.Simulate in Bolt in order to do authoritative movement using Unity's physics with rigid bodies?
I think it would be really difficult to achieve this with the current structure/architecture. The reason for this is that **Physics.Simulate** is a global simulation step and simulates all world at once and I will doubt we will see Unity adding support to simulate only parts of the world manually in the near future, that is a hard thing to achieve in any physics engine. Instead we could adapt Bolt for the job.
They way Bolt achieves authoritative movement is with the pair of callbacks **SimulateController** and **ExecuteCommand**. I hope I got this right. They work fine as long as the movement is predictible and can be reproduced if same input is reapplied. So right now **SimulateController** is collecting input state, store it in a command and send it at the same time to the local entity and to the server. **ExecuteCommand** will run both locally, on the controlled entity and on the server, and the state of the command (the command result) is updated at the end of the **ExecuteCommand** callback. The result of running the command on the server is then used on the controlled entity to do a correction, state is reset and the following input for the following frames up to the current one is executed again, fast forwarding to present. This is all working well as long updated state for an entity can be retrieved immediately during **ExecuteCommand** and it is also the reason we cannot do authoritative movement with **Physics.Simulate** step this way. In order to make **Physics.Simulate** work with Bolt we need to be able to retrieve the state of the commands (the result) after the physics are stepped. The current implementation executes commands and collects results one by one.

What I'm suggesting is adding a new callback "**UpdateCommand**" to be used alongside **SimulateController** and **ExecuteCommand**. The sequence of event would be:
1. **SimulateController** on the client
2. The input collected through commands it sent to both the server and locally like before
3. _On the server_
	- **ExecuteCommand** is called once for each entity but the command state is not updated inside **ExecuteCommand** 
	- after all **ExecuteCommands** are called, call a callback "**SimulateWorld**" or whatever name and run **Physics.Simulate** inside, this would be called only once per Bolt frame
	- after simulation has been stepped call **UpdateCommand** for each entity and in here update the state of the commands
  _On the client_
    - **ExecuteCommand** first with **resetState** set to "**true**" to reset state for each controlled entity (usually one but who knows), don't update command state here
    - call global **SimulateWorld** callback to advance simulation step
    - call **UpdateCommand** where we update state
    - for each remaining frame up to current repeat the steps above with **resetState** set to "**false**" and fast forward the simulation

With these rather small changes we should be able to have authoritative movement using Unity's own physics engine.
I'm not certain/confident that this will work properly but without a way of updating command results after simulation step we cannot tell.
Please note that I didn't mention anything about proxy entities (ones that are neither owned nor controlled by the client). The will be represented with kinematic rigidbodies and they will only replicate server state, no simulation needed on them. They will probably affect global simulation step, and it might cause troubles when fast forwarding but as I said above we will have to try it to know for sure.
I hope I didn't wrote nonsense here and that this could be something achievable.
Regards,
Catalin

**Comment by fholm** [comment]
This is not possible to implement currently because doing Physics.Simulate on the controlling client to re-play commands will cause the rest of the world on the clients to run at Nx times the speed where N is the about of commands you have in your buffer. 

Doing this would mean that you could never use any dynamic rigidbodies on the clients other than your one single player character, which is to harsh of a limitation.

**Comment by heretique** [comment]
Hmm, I see, that's a good point indeed. I wasn't considering other dynamic rigidbodies as it is not an issue in my case but I see how this is really limiting. So basically there is no easy solution without the ability to only advance parts of the world in the simulation step or to write my own stuff for collision detection and resolution?

**Comment by fholm** [comment]
The only viable solution is the one already used in the bolt samples, and that is to use a CharacterController component, and on top of that you'll have to manually implement all the physics interactions you need.

**Comment by herpdederp** [comment]
Just FYI I have this working with the new beta. https://www.youtube.com/watch?v=78XrhX3msNI&feature=youtu.be
