### ISSUE TITLE
Some Property types do not display correct arrow for expanded/collapsed properties

### ISSUE THREAD

**Issue by tmilker** [BoltEngine/Bolt-Tracker#35]
###How to reproduce issue
1. Open Window->Bolt->Assets
2. Create a new State or edit an existing one
3. Click New Property
4. Change type to one of: Color|Color32|Entity|Guid|Matrix4x4|NetworkId|PrefabId|ProtocolToken

###Expected Behavior
When the Property is created, the field section is expanded, the arrow indicator should be pointed down.  When you click the arrow, it should change to point to the right when collapsed or pointed down when expanded.

###Actual behavior
Arrow to left of Property name is pointed to the right instead of down when expanded.  It doesn't change when you click it to expand or collapse the information.

###Configuration
Unity Version: 5.5.2f1
Bolt Version: 1.0.0.4
Operating System: Windows 10 Pro 64-bit
Network Configuration: N/A

**Comment by ramonmelo** [comment]
Fixed on the next release.
