### ISSUE TITLE
Photon Cloud - Relay Failing 

### ISSUE THREAD

**Issue by DMeville** [BoltEngine/Bolt-Tracker#36]
I have not been able to reproduce this error locally, however I have had many players (~30%) reporting that relay was failing for them resulting in not being able to join any games.

Through logging what was going on while connecting (using google events to track in real time) and a handful of log files from players who provided them, I found that in most cases when a direct connection would fail (or perhaps some other reason mid direct connect), client state would go back to "JoinedLobby", resulting in the subsequent relay connect to immediately fail.

Adding the below code in PhotonPoller::JoinSessionRoutine after _currentConnectRoutine = null, and before the ChangeState(ConnectState.RelayPending) seems to fix this issue and makes sure the player has joined the room before connecting.  Further testing is needed to confirm this fix works in all cases, but since this fix has been pushed out to my players no relay connections have failed.

     if(_lbClient.State != ClientState.Joined){
            ChangeState(ConnectState.JoinRoomPending);
            LoadBalancerClient.OpJoinRoom(session.HostName); 
            timer = new Timer(ROOM_JOIN_TIMEOUT);
            while(_lbClient.State != ClientState.Joined && timer.Waiting) {
                yield return null;
            }
        }

        if(_lbClient.State != ClientState.Joined) {
            _currentConnectRoutine = null;
            Debug.Log("Failed to join room");
            ChangeState(ConnectState.Idle);
            yield break;
        }

**Comment by herpdederp** [comment]
Fixed in 1.0.0.5
