### ISSUE TITLE
Photon Cloud - Client disconnect causes ALL other clients to disconnect

### ISSUE THREAD

**Issue by DMeville** [BoltEngine/Bolt-Tracker#37]
###How to reproduce issue
1. Download Bolt from asset store
2. Run the Photon menu, create one server and two (or more) clients, connect them.
3. Disconnect one client by closing the window.

###Expected Behavior
Only the client that closed his window should be reported as disconnected.

###Actual behavior
Everyone except the host (all connected clients) get disconnected.  Disconnected Bolt callback is triggered on every client.  Checking the connection property passed in with the callback against BoltNetwork.server returns true, even though it was NOT the server that disconnected, but another client.

Digging into PhotonPoller, the issue seems to be related to the OnEventAction method.  Specifically:
case 254: if (BoltNetwork.server != null) BoltNetwork.server.Disconnect(); break;

Replacing that code with 
case 254:
            if(BoltNetwork.server != null) {
                if((int)obj.Parameters[ParameterCode.ActorNr] == 1) {
                    BoltNetwork.server.Disconnect();
                }
            }
            break;

ParameterCode.ActorNr seems to always be 1 for the server, so if we're a client (BoltNetwork.server != null) and it was the server that disconnected, we disconnect the client too.  Seems to work mostly fine, however it feels like a messy workaround.  Rather than signaling to the server that he is leaving, we just leave and wait for the server to realize the connection left and eventually times out, which then the server realizes it was a disconnect.

I have successfully uses this modified code to let clients leave mid game, which then gets detected by the server and replaces those players with bots until the game ends.

###Configuration
Unity Version: 5.5.2f1
Bolt Version: 1.0.0.4
Operating System: -
Network Configuration: -

**Comment by herpdederp** [comment]
Fixed in 1.0.0.5
