### ISSUE TITLE
Bolt breaks unhelpfully with Newtonsoft JSON.net

### ISSUE THREAD

**Issue by cjddmut** [BoltEngine/Bolt-Tracker#38]
###How to reproduce issue
1. Follow tutorial [101](https://doc.photonengine.com/en-us/bolt/current/getting-started/bolt-101-getting-started) to completion
2. Build and run, cubes will appear on client and server
3. Add [Newtonsofts JSON](http://www.newtonsoft.com/json) serializer dll to the project
4. Rebuild and run, game breaks when client connects

###Expected Behavior
Game should not break! Or at least, a helpful message about compatibility with this common easy to google json .net dll

###Actual behavior
Game throws exceptions when client connect and cube does not appear.

```
NullReferenceException: Object reference not set to an instance of an object
  at Bolt.PropertyFloatCompressionSettings.Pack (UdpKit.UdpPacket stream, Single value) [0x00000] in <filename unknown>:0 
  at Bolt.PropertyVectorCompressionSettings.Pack (UdpKit.UdpPacket stream, Vector3 value) [0x00000] in <filename unknown>:0 
  at EntityChannel.PackUpdate (Bolt.Packet packet, .EntityProxy proxy) [0x00000] in <filename unknown>:0 
  at EntityChannel.Pack (Bolt.Packet packet) [0x00000] in <filename unknown>:0 
  at BoltConnection.Send () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)
NullReferenceException: Object reference not set to an instance of an object
  at Bolt.PropertyFloatCompressionSettings.Pack (UdpKit.UdpPacket stream, Single value) [0x00000] in <filename unknown>:0 
  at Bolt.PropertyVectorCompressionSettings.Pack (UdpKit.UdpPacket stream, Vector3 value) [0x00000] in <filename unknown>:0 
  at EntityChannel.PackUpdate (Bolt.Packet packet, .EntityProxy proxy) [0x00000] in <filename unknown>:0 
  at EntityChannel.Pack (Bolt.Packet packet) [0x00000] in <filename unknown>:0 
  at BoltConnection.Send () [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
BoltLog:Exception(Exception)
BoltConnection:Send()
BoltCore:Send()
BoltSend:FixedUpdate()
 
(Filename:  Line: -1)
```

###Configuration
Unity Version: 5.6.0f3
Bolt Version: 1.0.0.4 (DEBUG)
Operating System: Windows 10
Network Configuration: N/A

**Comment by fholm** [comment]
I just tested this on Unity 5.6.1, with bolt 1.0.0.6 (DEBUG), Windows 10  using the Newtonsoft.JSON dll for .NET 3.5, i can't repro this. Do you have a repro project you could send us?

**Comment by fholm** [comment]
Forgot the support e-mail: support@boltengine.com If you can send a repro case and write "Github Issues #38 Repro" as the title.

**Comment by fholm** [comment]
Tried this again with a different Newtonsoft.JSON dll, and everything still runs properly for both client and server, I need a project with a repro case to find and fix this.

**Comment by herpdederp** [comment]
This DLL also breaks Bolt
https://github.com/icsharpcode/NRefactory 
[ICSharpCode.NRefactory.zip](https://github.com/BoltEngine/Bolt-Tracker/files/1901367/ICSharpCode.NRefactory.zip)

**Comment by laurelhach** [comment]
I have Bolt 1.1.0.0 and Unity 2017.3.1.
I don't have any issue with Json.
I use the following version: 10.0.3 (Net 2.0)

You could try to find another version of Json and you could also update your Bolt. The new version is pretty stable I think.

**Comment by herpdederp** [comment]
@laurelhach I just tested with a DLL from here. https://github.com/JamesNK/Newtonsoft.Json/releases

As soon as you connect a client to a host it will break.

**Comment by laurelhach** [comment]
hmm.. Can you upgrade bolt? Or Unity? Might not be what you want.
Also, Did you try different version of Json? I have multiplayer working, can connect on a host using steam and or two standalone version (on the same computer).

**Comment by herpdederp** [comment]
@laurelhach not following

**Comment by herpdederp** [comment]
Found a third example that breaks Bolt: Amazon Gamelift .DLLs

**Comment by 0bytedna** [comment]
@herpdederp I have the same issue. Any fix? I am applying for Indie games accelerator program from Google. I need this issue to be fixed before the deadline. :sob:
https://events.withgoogle.com/indie-games-accelerator/

**Comment by herpdederp** [comment]
Fixed with 1.1.0.9

**Comment by 0bytedna** [comment]
@herpdederp thanks. New version is released?

**Comment by fholm** [comment]
Some time next week probably
