### ISSUE TITLE
Command correction interpolation

### ISSUE THREAD

**Issue by herpdederp** [BoltEngine/Bolt-Tracker#4]
1) The PropertyCodeEmitter is hardcoded to output "false" for the interpolation settings on command, no matter the setting in the UI. 
2) There is no exposed UI for altering the SnapMagnitude.
3) Only Vector3 has a SmoothCommandCorrection implementation. If one uses a different type that allows interpolation (like Quaternion) and has a non-zero value for the number of interpolated frames, the server results are simply discarded because they are stored in SmoothStorageTo and never copied to Storage where the values that end up being used need to go.

https://github.com/fdreher/bolt/commits/Command_Correction_Interpolation

**Comment by TSchmGIT** [comment]
In addition and even worse, it seems that the proper result state is not replicated at all. I tested this for a float property. Haven't run full unit tests to confirm, but this would be a major issue. I suggest to either fix that fast or disable this property since it messes up the replication.

**Comment by herpdederp** [comment]
fixed in 0.4.3.14
