### ISSUE TITLE
Hashtable is ambiguous reference

### ISSUE THREAD

**Issue by lghenk** [BoltEngine/Bolt-Tracker#41]
```
Assets/photon/PhotonLoadbalancingApi/LoadBalancingPeer.cs(430,69): error CS0104: `Hashtable' is an ambiguous reference between `System.Collections.Hashtable' and `ExitGames.Client.Photon.Hashtable'
```

```
Assets/photon/PhotonLoadbalancingApi/Player.cs(117,16): error CS0104: `Hashtable' is an ambiguous reference between `System.Collections.Hashtable' and `ExitGames.Client.Photon.Hashtable'
```

```
Assets/photon/PhotonLoadbalancingApi/Room.cs(296,49): error CS0104: `Hashtable' is an ambiguous reference between `System.Collections.Hashtable' and `ExitGames.Client.Photon.Hashtable'
```

In total there are 15 errors. But those are the files the errors are located in.

### How to reproduce issue
1. Install unity 2017.1.0f1
2. Import Photon Bolt

Note: Yes i am aware that i am running the beta version but i thought it can't hurt to report it anyway.

### Configuration
Unity Version: 2017.1.0f1
Bolt Version: 1.0.0.5
Operating System: Windows 10
Network Configuration:

**Comment by zhuchun** [comment]
Here is a workaround
Add "UNITY;" into File - Build Settings - Player Settings - Other Settings -Scripting Define Symbols
