### ISSUE TITLE
Change latency simulation w/o BoltLauncher.StartServer

### ISSUE THREAD

**Issue by anttiluukka** [BoltEngine/Bolt-Tracker#42]
There appears to be no way to change BoltConfig settings without BoltLauncher.StartServer.

I would like to change the latency simulation at any time without shutdown + start server.

Any way to make the config more accessible, so we could alter the settings at any time (at least the latency simulation)?

**Comment by fholm** [comment]
This has been exposed as BoltNetwork.SetNetworkSimulation now, will be available in 1.1.0.0 - note that it needs to be called on every connected computer individually, there is no way   to call it on for example the server and have the clients receive this update automatically. 

It's also only available in DEBUG DLLs, not in release.

**Comment by herpdederp** [comment]
1.1 is now released
