### ISSUE TITLE
Latest version broke animation damping time

### ISSUE THREAD

**Issue by 0x-1** [BoltEngine/Bolt-Tracker#43]
###How to reproduce issue
1. Create State with float Bolt Animation parameter
2. add damping to it
3. compile and recieve error about method not taking 5 arguments (4 works without damping)

###Expected Behavior
Bolt should compile

###Actual behavior
Error message on compile

###Configuration
Unity Version: 2017.1.0f3
Bolt Version: 1.0.0.6
Operating System: Win10 64bit
Network Configuration: same as before

**Comment by fholm** [comment]
So I looked into this today, I can't reproduce it. See the attached screenshot if I've missed something, but I think i followed your instructions correctly and compile works fine.

![image](https://user-images.githubusercontent.com/141683/29667522-0425d78c-88dd-11e7-8972-45379d0d12e7.png)

**Comment by Suncheck** [comment]
I encountered this issue a month ago, too, and still waiting for a fix.
Today I've looked into it again, just to bring better information for you, and found out what's going wrong.

It seems that Unity 2017 is using the local format of numbers for all the text fields.
English: 0.05
for example German: 0,05

And your script copying the "0,05" into the project.cs and it looks like an additional argument. If I use just "1" for example it will work.

![bolterror](https://user-images.githubusercontent.com/12831156/29883209-d2badec2-8daf-11e7-8e02-30085936071c.png)

Hope that helps to fix it really soon!

**Comment by fholm** [comment]
Okey, so this seems like an issue that has popped up on some platforms with Unity 2017. I have made sure that the strings are formatted with the invariant culture (which should ensure the `0.0` syntax over the faulty `0,0` syntax) when the code is generated. The fix will be available in next release (1.1.0.0)

**Comment by 0x-1** [comment]
Yes. Unity 2017 could have caused this issue as I did not change the configuration between the updates. on my German unity/OS. I overlooked this when reviewing the config for sure.

~0x-1
