### ISSUE TITLE
LAN Sessions does not get removed from the SessionList if the server stops broadcasting

### ISSUE THREAD

**Issue by alxcyl** [BoltEngine/Bolt-Tracker#44]
### How to reproduce issue
(A) Starting the server
1. Connect as a SERVER.
2. Call `BoltNetwork.EnableLanBroadcast()` on the SERVER.
3. Call `BoltNetwork.SetHostInfo()` on SERVER.

(B) Starting the client
1. Connect as a CLIENT.
2. Call `BoltNetwork.EnableLanBroadcast()` on the CLIENT.
3. Observe `BoltNetwork.SessionList.Count`.
4. It should display at least one (1) session available.

(C) Triggering the bug
1. On the SERVER, call `BoltNetwork.DisableLanBroadcast()`.
2. On the CLIENT, notice the session count is still 1.
3. On the SERVER, connect as SERVER once again.
4. On the CLIENT, notice the session count is now 2.
5. On the SERVER, call `BoltLauncher.Shutdown()`.
6. On the CLIENT, notice the session count remains at 2.

A sample project demonstrating the issue can be found here: https://drive.google.com/file/d/0B3vVplmhHeeoQWJHbkQ3SFNrMW8/view?usp=sharing

Build the project and deploy it in two different machines. Use one machine as the client and the other machine as a server.

### Expected Behavior
- When the SERVER calls `BoltNetwork.DisableLanBroadcast()`, the CLIENT's `BoltNetwork.SessionList` should not contain the SERVER's last broadcasted session.
- When the SERVER shuts down or forcibly closes (e.g. Alt-F4), the CLIENT's `BoltNetwork.SessionList` should not contain the SERVER's last broadcasted session.

### Actual behavior
- The SERVER's last broadcasted session remains on the CLIENT's BoltNetwork.SessionList even though it's not a "valid" session anymore.

### Configuration
- Unity Version: 5.5.4p3
- Bolt Version: 1.0.0.4
- Operating System: Windows 10 OEM
- Network Configuration: LAN over WiFi

**Comment by 0bytedna** [comment]
any fix for this yet???

**Comment by 0bytedna** [comment]
any update on this? Its been a year..:unamused:

**Comment by ramonmelo** [comment]
Fixed on the next release.
