### ISSUE TITLE
BoltNetwork.Instantiate does not use rotation parameter.

### ISSUE THREAD

**Issue by ghost** [BoltEngine/Bolt-Tracker#46]
###How to reproduce issue
1. BoltNetwork.Instantiate a prefab. 
2. Add rotation parameter.

###Expected Behavior
Should replicate the rotation passed in.

###Actual behavior
Instead, sets rotation to default rotation.

###Configuration
Unity Version: 2017.1
Bolt Version: 1.0.0.6
Operating System: Windows 10
Network Configuration: Photon Cloud

**Comment by herpdederp** [comment]
Can't repro. If you can, send us a project with the behavior you're reporting.
