### ISSUE TITLE
Connecting to a server from the SessionList does not use LAN when available

### ISSUE THREAD

**Issue by adamscoble** [BoltEngine/Bolt-Tracker#48]
###How to reproduce issue
1. Start a server on a LAN network with internet access and Photon Relay
2. Connect to the server from another computer using the SessionList item (HasLAN is also false).

###Expected Behavior
Connection should be made over LAN.

###Actual behavior
Connection is made over Photon Relay.

###Configuration
Unity Version: 2017.2.0f3
Bolt Version: 1.1.0.0
Operating System: Windows/OSX
Network Configuration: Multiple computers connected to router

**Comment by herpdederp** [comment]
Fixed in 1.1.0.3
