### ISSUE TITLE
Quaternion and Vector Array property smoothing broken

### ISSUE THREAD

**Issue by dlorddd** [BoltEngine/Bolt-Tracker#50]
Summary: The functionality of the smoothing algortihms for certain properties don't work as intended. This includes quaternion, vector array and quaternion array properties.

###How to reproduce issue
1. Load a project
2. Create a state with a quaternion property
3. Set the property smoothing algorithm to interpolation
4. Create a state with a vector array property
5. Set the property smoothing algorithm to interpolation
_NEW:_
6. Create a state with a quaternion array property
7. Set the property smoothing algorithm to interpolation

###Expected Behavior
The quaternion property should follow the changes smoothly on a client.
The vector array property should follow the changes smoothly on a client.
The quaternion array property should follow the changes smoothly on a client.

###Actual behavior
The quaternion property always returns an identity quaternion on a client.
The vector array property returns values smoothly, but some values appear to be overwritten by other values so that some values are "lost" and some values are copies of other values on a client.

Server sends the property to [(0,0,0), (1,1,1), (2,2,2), (3,3,3)]
Client receives the property as [(0,0,0), (1,1,1), **(1,1,1)**, (3,3,3)]

The quaternion array property always returns an identity quaternion on a client.

###Configuration
Unity Version: 2017.1.2f1
Bolt Version: 1.1.0.0
Operating System: Windows 10 Home (10.0.16299 Build 16299)
Network Configuration: Multiple computers over router, multiple computers over Photon relay.

**Comment by ramonmelo** [comment]
Fixed on the next release.

Thanks for the feedback.
