### ISSUE TITLE
Exception when _lbClient is destroyed while joining

### ISSUE THREAD

**Issue by Maedgev** [BoltEngine/Bolt-Tracker#51]
###How to reproduce issue
1. Try to connect to a server while being on a poor internet connection
2. Shutdown Bolt while it's waiting to connect to a room in JoinSessionRoutine

###Expected Behavior
I should either succeed or fail connecting to the server.

###Actual behavior
We get an exception at PhotonPoller:691 because _lbClient is null
while (_lbClient.State != ClientState.Joined && timer.Waiting)

###Suggested fix
Add a null check before checking state, and then do a yield break right after if _lbClient is null.

###Configuration
Unity Version: 2017.3
Bolt Version: 1.1.0.0
Operating System: Win10

**Comment by ramonmelo** [comment]
Fixed. The updated code will be on the next version.

Thanks for the feedback.
