### ISSUE TITLE
State's property "Array of Floats" with interpolation has wrong values (0) when getting it

### ISSUE THREAD

**Issue by vlab22** [BoltEngine/Bolt-Tracker#53]
###How to reproduce issue
1. Create a State
2. add a property Array of floats (length of 20 its ok) Ex: name **MyFloats**
3. set Interpolate "As Float"
4. Set any values to arrayindices of array of floats, maybe a "for" over all items
5. Try get values from array indices

###Expected Behavior

In Boltentity (inspector):
```
MyFloats[0] = 23.67
MyFloats[1] = 2.54
MyFloats[2] = 3.6
MyFloats[3] = 78.7
MyFloats[4] = 246.67
```
Getting the array elements, could be with a "for" in state.MyFloats,
```
MyFloats[0] = 23.67
MyFloats[1] = 2.54
MyFloats[2] = 3.6
MyFloats[3] = 78.7
MyFloats[4] = 246.67
```

###Actual behavior

The array of floats is OK in BoltEntity in inspector, but when we try to get a value, a strange behavior happens.
Example :

In Boltentity (inspector):
```
MyFloats[0] = 23.67
MyFloats[1] = 2.54
MyFloats[2] = 3.6
MyFloats[3] = 78.7
MyFloats[4] = 246.67
```

Getting the array elements, could be with a "for" in state.MyFloats, the values are buggy (shift)
```
MyFloats[0] = 23.67   <-- index 0 in boltentity
MyFloats[1] = 0       <-- ???
MyFloats[2] = 2.54    <-- index 1 in boltentity
MyFloats[3] = 0       <-- ??? 
MyFloats[4] = 3.6     <-- index 2 in boltentity
MyFloats[5] = 0       <-- ??? 
MyFloats[6] = 78.7    <-- index 3 in boltentity
MyFloats[7] = 0       <-- ???
MyFloats[8] = 246.67  <-- index 4 in boltentity
```

If disable "interpolation" in the array property, works fine.
So "interpolation" is buggy when get values.

###Configuration

Unity Version: Unity 2017.3.0f3 (64-bit)
Bolt Version: 1.1.0.0
Operating System: Win10 Pro (64-bit)
Network Configuration: --

**Comment by ramonmelo** [comment]
Fixed on the next release.

Thanks for the feedback.
