### ISSUE TITLE
Direct connect not working in Bolt 1.1.0.1

### ISSUE THREAD

**Issue by Nox89** [BoltEngine/Bolt-Tracker#55]
###How to reproduce issue
1. Import Bolt 1.1.0.1 in Unity
2. Install Bolt + Cloud including samples
3. Start a server
4. Connect with a client from the same machine

###Expected Behavior
The client should (hopefully) connect with Direct (punchthrough).

###Actual behavior
The client never gets any sessions from Zeus and therefor can't attempt punchthrough, instead it connects through Relay.

###Note
Running the exact same test with 1.1.0.0 sample works fine and connects directly (no relay) as expected.

###Configuration
Unity Version: 2017.3.0f3
Bolt Version: 1.1.0.1
Operating System: Windows 10
Network Configuration:

**Comment by herpdederp** [comment]
Resolved in 1.0.0.2
