### ISSUE TITLE
Hitbox distance messes up if parent scale isn't 1, 1, 1

### ISSUE THREAD

**Issue by PleaseFuckOff** [BoltEngine/Bolt-Tracker#57]
###How to reproduce issue
1. Make the parent of a hitbox something other than 1, 1, 1.

###Expected Behavior
Distance check should come out as normal.

###Actual behavior
Distance returns a weird number thus resulting in shooting through walls.

###Configuration
Unity Version: Unity 2017.3
Bolt Version: Bolt 1.1.0.0
Operating System: Windows 10
Network Configuration:  Any

**Comment by herpdederp** [comment]
Duplicate #25
