### ISSUE TITLE
BoltStartFailed callback doesn't work

### ISSUE THREAD

**Issue by paul-utkin** [BoltEngine/Bolt-Tracker#58]
###How to reproduce issue
1. create new Unity project with Photon Bolt installed and default Bolt settings
2. create new script, attach it to Main Camera
3. paste this code to previously created file:

```
using Bolt;
using UdpKit;
using UnityEngine;

public class NetManager : GlobalEventListener {

	void Start() {
		var endpoint = UdpEndPoint.Parse("11.22.33.44:5555");
		BoltLauncher.StartServer(endpoint);
	}

	public override void BoltStartFailed() {
		Debug.Log("Server failed to start");
	}

	public override void BoltStartDone() {
		Debug.Log("Server started");
	}

}
```

4. Press "Play"

###Expected Behavior
Bolt server fails to start, message "Server failed to start" appears in console, indicating that BoltStartFailed() callback was fired

###Actual behavior
Bolt server fails to start, message "Server failed to start" does not appear in console, indicating that BoltStartFailed() callback wasn't fired

###Configuration
Unity Version: 2018.1.0b13
Bolt Version: 1.1.0.5 (debug)
Operating System: Windows 10 Pro
Network Configuration: any

**Comment by ramonmelo** [comment]
Fixed on the next release.

Thanks for your feedback.
