### ISSUE TITLE
SetHostInfo() throws a NullReferenceException when called inside BoltStartDone() callback

### ISSUE THREAD

**Issue by 0bytedna** [BoltEngine/Bolt-Tracker#60]
I came across this issue after upgrading from 1.0.0.5. 

###How to reproduce issue
1. Connect as a SERVER.
2. Call BoltNetwork.SetHostInfo() inside BoltStartDone() callback

###Expected Behavior
It should set provided server info

###Actual behavior
Throws a NullReferenceException. 

NullReferenceException: Object reference not set to an instance of an object
PhotonPoller+<SetHostInfoRoutine>c__Iterator1.MoveNext () (at Assets/photon/PhotonPlatform/PhotonPoller.cs:647)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
PhotonPoller:SetHostInfo(String, Boolean, Object) (at Assets/photon/PhotonPlatform/PhotonPoller.cs:640)
PhotonPlatform:HandleSetHostInfo(String, Boolean, Object)
BoltCore:SetHostInfo(String, Boolean, IProtocolToken)
BoltNetwork:SetHostInfo(String, IProtocolToken)
Photon.PhotonInit:BoltStartDone() (at Assets/bolt_samples/NEW-PhotonCloud/scripts/PhotonInit.cs:49)
BoltInternal.GlobalEventListenerBase:BoltStartDoneInvoke()
BoltCore:Udp_SocketStartupDone(UdpEventStartDone)
BoltCore:PollNetwork()
BoltCore:Poll()
BoltPoll:FixedUpdate()

###Configuration
Unity Version: Unity 2017.2.0f3
Bolt Version: 1.1.0.5
Operating System: Windows 10 Pro
Network Configuration: WAN

###Repo Project Link
https://www.dropbox.com/s/7ugsx49ytxkmavt/Bolt%20Samples.zip?dl=0

Steps
Run PhotonTutorial scene and start as server. Check console for NullReferenceException

**Comment by ramonmelo** [comment]
Are you using Photon Cloud ? If yes, you must call `SetHostInfo` *before* starting the server.

When calling `SetHostInfo`, the Photon client + Photon room are created, and then the server can run as normal.

**Comment by 0bytedna** [comment]
It's strange because it worked fine in 1.0.0.5

**Comment by 0bytedna** [comment]
@ramonmelo In the previous versions, I called SetHostInfo after starting the server. It worked fine. What changed in newer version?

**Comment by ramonmelo** [comment]
Which version worked for you ? 

But I will take a better look on this.
Thanks for your report.

**Comment by DMeville** [comment]
Question:
I have not tested this, but was planning up upgrading from 1.0.0.4 to the most recent version. From this issue I imagine I would run into a similar problem.

For example: I use BoltNetwork.SetHostInfo (using photon cloud) to update the room data (like number of player slots available).  This data needs to be available on the server list and before a client attempts to join the server, so that they don't try to join servers that are already full.  This data needs to also be updated by the server when new players.

If SetHostInfo can no longer be called after starting the server, what is the alternative?

**Comment by 0bytedna** [comment]
@DMeville call it before starting the server (I doubt it will work, since bolt isn't running yet). Other option is this

**Comment by 0bytedna** [comment]
@ramonmelo no issues with the new PhotonPoller.cs

**Comment by ramonmelo** [comment]
@0bytedna thx!

**Comment by garrettshields** [comment]
@ramonmelo The new PhotonPoller fixed the null reference exception, but now my session is not getting published to Photon.
