### ISSUE TITLE
BoltNetwork.RegisterShutdownDoneCallback needs to do something, be removed, or at least give a compiler warning for depreciation. 

### ISSUE THREAD

**Issue by cjddmut** [BoltEngine/Bolt-Tracker#64]
###How to reproduce issue
1. Invoke BoltNetwork.RegisterShutdownDoneCallback()

###Expected Behavior
Tell us what should happen
Either works or shouldn't exist

###Actual behavior
Function exists but is empty. This is confusing.

(Decompiled)
![image](https://user-images.githubusercontent.com/2998383/39497594-e788078a-4d58-11e8-8118-474fec589b2e.png)

###Configuration
Unity Version: 2017.3.0f3
Bolt Version 1.0.0.6
Operating System: Win10
Network Configuration:

**Comment by herpdederp** [comment]
This is fixed on the next release.
