### ISSUE TITLE
iOS build won't connect

### ISSUE THREAD

**Issue by aidanwolf** [BoltEngine/Bolt-Tracker#65]
###How to reproduce issue
1. Import Photon Bolt from Asset Store
2. Import iOS packages, sample packages
3. Build Advanced sample for iOS
4. Deploy to 2 devices and run

###Expected Behavior
Server starts
Client connects to Server

###Actual behavior
Server starts, loads scene
Server isn't discoverable/Client doesn't connect to Server
Client debug console spams "retry connect.."
Client never loads scene
Times out

**Debug Console**
iOS Client/Server: `Could not resolve a possible LAN address by inspecting local network interfaces` 
Editor: `LAN endpoint resolved as [Endpoint ...`

I'm assuming the server fails to create a LAN endpoint, so the client fails to discover it

###Configuration
Unity Version: 2018.1.0f2
Bolt Version: 1.1.0.5
Operating System: iOS (Built on MacOS)
Network Configuration: Wifi

**Here's a video preview of what's happening**

[Screen recording of server on iPad (11.0)](https://www.dropbox.com/s/kgcktktf6hxcuna/server.MOV?dl=0) 
[Screen recording of client on iPhone 6s (11.3)](https://www.dropbox.com/s/byeoxr0w762mkqm/client.MOV?dl=0)

**Here's a simple sample to reproduce the problem on iOS:**

[Xcode sample build](https://www.dropbox.com/s/3vxovqbd5o8rhgl/boltsample.zip?dl=0)

**Comment by herpdederp** [comment]
@aidanwolf You cannot share the contents of Photon Bolt publicly, it is a paid asset.

**Comment by ramonmelo** [comment]
Please, verify in the Bolt Settings if the `Accept Mode` is set to `Auto`.

**Comment by aidanwolf** [comment]
@ramonmelo [Accept Mode is set to Auto](https://www.dropbox.com/s/z8x3lh1tie0f86a/Screenshot%202018-05-02%2020.33.03.png?dl=0)

**Comment by aidanwolf** [comment]
**Logs:**
[Xcode log (Server)](https://paper.dropbox.com/doc/Sample-Logs-TsMVxpOWBmLbldfmaJyZV#:uid=992221398737605863126106&h2=Server)
[Xcode log (Client)](https://paper.dropbox.com/doc/Sample-Logs-TsMVxpOWBmLbldfmaJyZV#:uid=989858892705685634953402&h2=Client)
