### ISSUE TITLE
Bolt Scenes - "Debug Start" MissingMethodException

### ISSUE THREAD

**Issue by Kerrjgan** [BoltEngine/Bolt-Tracker#67]
###How to reproduce issue
1. Install Bolt from Asset Store
2. Add scene(s) to build settings
3. Try to open Bolt Scenes Window

###Expected Behavior
Debug Start should work, no errors in the console.

###Actual behavior
Consistent stream of the same error message while the Bolt Scenes editor window is open. Nothing happens when I try to press Debug Start

`MissingMethodException: Method not found: 'UnityEditor.BuildPipeline.BuildPlayer'.
BoltScenesWindow.Update ()
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:291)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:284)
UnityEditor.HostView.SendUpdate () (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:363)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:183)`

###Configuration
Unity Version: 2018.11.0f2
Bolt Version: 1.1.0.5
Operating System: Windows 10

**Comment by herpdederp** [comment]
fixed in next release
