### ISSUE TITLE
Float Property smoothing does not work

### ISSUE THREAD

**Issue by JulianKaulitzki** [BoltEngine/Bolt-Tracker#68]
###How to reproduce issue
1. Just add a Float-Property to a random state and set the smoothing to 'Interpolation'.

###Expected Behavior
Tell us what should happen
The value should be smoothed out.

###Actual behavior
Tell us what happens instead
The value is not smooth.
As a workaround I am using a Vector3-Property where the Axes are set to 'X' in order to achieve the smoothed float effect 

###Configuration
Unity Version: 2017.3.p1
Bolt Version: 1.1.0.0
Operating System: Windows 10
Network Configuration:

**Comment by ramonmelo** [comment]
Fixed on the next release.

Thanks for your feedback.
