### ISSUE TITLE
Suspecting that Bolt's Temporal Anti-aliasing isn't working

### ISSUE THREAD

**Issue by Yokogeri94** [BoltEngine/Bolt-Tracker#69]
###How to reproduce issue
1. Follow this guide: 
[https://doc.photonengine.com/en-us/bolt/current/in-depth/temporal-anti-aliasing](https://doc.photonengine.com/en-us/bolt/current/in-depth/temporal-anti-aliasing)
2. Observe that the micro-stutter still seems to be there.

###Expected Behavior
The micro-stutter should disappear.

###Actual behavior
The micro-stutter still seems to be there.

###Configuration
Unity Version: 2018.1.0f2
Bolt Version: 1.1.0.6
Operating System: Windows 10 x64

**Comment by fholm** [comment]
Are you testing this in Editor or in Builds? The editor commonly has some microstuttering on a lot of computers.

**Comment by Yokogeri94** [comment]
It was in the editor, but I tried creating a build and seem to have the same problem.

If anything, the temporal anti-aliasing seems to make my jitter even worse?
Only seems to be on the client though.

I'll send you two builds through a PM on the Bolt Discord so you can compare!

**Comment by fholm** [comment]
We spoke on Discord, turns out it was user error :)
