### ISSUE TITLE
Incorrect Connection Count in UdpSession (BoltNetwork.SessionList)

### ISSUE THREAD

**Issue by DaBossTMR** [BoltEngine/Bolt-Tracker#7]
###How to reproduce issue
1. First create a server, connect to Zeus (I'm using debug master server) and register to the session list (BoltNetwork.SetHostInfo()).
2. The session appears in the list as usual, and player is able to join
3. When player leaves the server, and refreshes the session list, the connection count still remains the same.

###Expected Behavior
Unless if there's a method that handles this that I have missed, the connection count should obviously decrement by 1 when a player leaves. I am using the Unity Editor, and I haven't tested with Standalone build but I'm assuming the same will happen. Basically, connection count should represent the actual amount of players to the server.

###Actual behavior
As stated above, it did not decrement by 1 when a player left. I already tried restarting the Unity Editor but it still showed the incorrect number.

Example: If 2 players join and leave, the player count will remain at 2 until the server is shutdown or if there are more than 2 players in the server.

###Configuration
Unity Version: 5.3.3f1 (in-editor)
Bolt Version: 0.4.3.13 (DEBUG)
Operating System: Windows 10
Network Configuration: Using the debug master server

**Comment by herpdederp** [comment]
I fixed this, will be in the next Bolt release
