### ISSUE TITLE
Expose connection metrics

### ISSUE THREAD

**Issue by trueinsider** [BoltEngine/Bolt-Tracker#70]
There is Window called Bolt Remotes in the Unity Editor which shows info for states/events/commands bytes In/Out.
To be able to report traffic metrics to our monitoring solution we need public properties/fields states/events/commands In/Out which will contain ever-growing values of bits/bytes sent during lifetime of this BoltConnection instance.

**Comment by DirtyHippy00** [comment]
Connection.BitsPerSecondIn / Out

Bolt uses a single packet on the send rate so everything you mention above is included in the packet.  So Bolt already gives you the bandwidth required.

**Comment by ramonmelo** [comment]
Hello, thanks for your feedback.

This feature will be on the next release of Bolt.
