### ISSUE TITLE
Change BoltPoll/Send debug instrumentation to use a float

### ISSUE THREAD

**Issue by DirtyHippy00** [BoltEngine/Bolt-Tracker#73]
Bolt.DebugInfo.PollTime = (float) BoltCore._timer.ElapsedTicks / (float) System.Diagnostics.Stopwatch.Frequency * 1000.0f;

Bolt.DebugInfo.SendTime = (float) BoltCore._timer.ElapsedTicks / (float) System.Diagnostics.Stopwatch.Frequency * 1000.0f;

will generate millseconds as a float which is more useful than an integer

**Comment by herpdederp** [comment]
this was changed ~6 months ago
