### ISSUE TITLE
BoltGlobalBehaviour Attribute doesn't work with Scene Parameters

### ISSUE THREAD

**Issue by fishingGrapes** [BoltEngine/Bolt-Tracker#75]
###How to reproduce issue
1. Decorate a GlobalEventListener Class with BoltGlobalBehaviour Attribute
2. Pass in the Scene Names you want the Behaviour to be Active In
3. Optionally, pass a BoltNetworkModes parameter to the attribute.

**Eg**. [BoltGlobalBehaviour(BoltNetworkModes.Server, "Tutorial_Menu", "Tutorial") ] 

###Expected Behavior
The Callbacks inside the GlobalEventListener class must be called in the Scenes mentioned in the BoltGlobalBehaviour Attribute parameters.

###Actual behavior
The Callbacks are not fired and Debug.Logs in the class are not executed.
The _BoltNetworkModes_ Parameter seems to work fine though.

###Configuration
Unity Version: 2018.1.2f1
Bolt Version: 1.0.0.7
Operating System: Windows 8
Network Configuration:

**Comment by herpdederp** [comment]
http://forum.photonengine.com/discussion/12029/problem-with-boltglobalbehaviour-attribute#latest
