### ISSUE TITLE
When Client Times Out Theres a Packet Read Bolt Assert Failure

### ISSUE THREAD

**Issue by cjddmut** [BoltEngine/Bolt-Tracker#76]
###How to reproduce issue
1. Download Project Zip At: deleted
2. Run boltbug.exe in out/ as SERVER
3. Open project in Unity, open scene Scenes/bug-disconnect-connection.unity, run and start as CLIENT
4. Once connected pause editor to force time out

###Expected Behavior
Something helpful? A message that a client timed out? Probably not an error that there was a packet misread.

###Actual behavior
This:
![image](https://user-images.githubusercontent.com/2998383/41448700-222f10d8-7011-11e8-9e49-7d596d419a9f.png)

###Configuration
Unity Version: 2017.3.0f3
Bolt Version: 1.0.0.6
Operating System: Windows 10
Network Configuration: Local

**Comment by herpdederp** [comment]
Please don't post Bolt source, it is a paid asset. You cannot share it publicly outside your studio.

**Comment by cjddmut** [comment]
My bad, updated sharing settings and sent to support email.

**Comment by fholm** [comment]
Is this 100% repro every time or randomly?

**Comment by cjddmut** [comment]
Appeared 100% to me in my primary project but only ran it once to confirm in the supplied simple project.

**Comment by ramonmelo** [comment]
The exception thrown was updated with one more descriptive (`BoltPackageOverflowException`). The disconnect reason received on the `Disconnect` callback was set to `UdpConnectionDisconnectReason.Timeout` along with a more clear message.

This will be available on the next release.
