### ISSUE TITLE
Temp\bolt\project.cs CS0101: The namespace `global::' already contains a definition for `IPlayerState'

### ISSUE THREAD

**Issue by myxibrium** [BoltEngine/Bolt-Tracker#78]
###How to reproduce issue
1. Follow instructions on https://doc.photonengine.com/en-us/bolt/current/getting-started/bolt-101-getting-started
2. When you get to the Compile Assembly step, you get the following error:
D:\GameDev\ProjectUtopia\Temp\bolt\project.cs(1605,18): error CS0101: The namespace `global::' already contains a definition for `IPlayerState'
UnityEngine.Debug:LogError(Object)
BoltUserAssemblyCompiler:ErrorDataReceived(Object, DataReceivedEventArgs)
System.Diagnostics.ProcessAsyncReader:AddInput()

This is due to multiple definitions of the interface IPlayerState.
The first definition looks like this:

public interface IPlayerState : Bolt.IState {
  Bolt.NetworkTransform PlayerTransform {
    get;
  }
}

The second definition is a bit longer, it looks something like this:

public interface IPlayerState : Bolt.IState {
  Bolt.NetworkTransform transform {
    get;
  }
  int team {
    get;
    set;
  }
  string name {
    get;
    set;
  }
.....
}

###Expected Behavior
You should get a validation error when trying to create a State with a conflicting or pre-existing name.

###Actual behavior
The UI allows creation of conflicting names for States.

###Configuration
Unity Version: 2017.3.1f1
Bolt Version: 1.1.0.7
Operating System: Windows 10
Network Configuration: Wifi

**Comment by fholm** [comment]
For 1.1.0.8 this has been fixed so that the compiler will check for duplicate asset names before it tries to run the C# compiler so you get a nicer error and not a random dump of C# compile errors. Making it warn during asset naming is a bit more complex due to how bolts asset structure works internally with the unity editor, but this new error should be much nicer.
