### ISSUE TITLE
Latency simulation only works client to server

### ISSUE THREAD

**Issue by adamscoble** [BoltEngine/Bolt-Tracker#79]
###How to reproduce issue
1. Enable latency simulation
2. Send a command client to server
3. Send a command server to client

###Expected Behavior
Both commands should take the same amount of time to reach their destination.

###Actual behavior
Client to server command is delayed by the latency simulation. Server to client command arrives instantly.

###Configuration
Unity Version: 2017.4.3
Bolt Version: 1.1.0.7
Operating System: Windows

**Comment by ramonmelo** [comment]
@adamscoble you still see this issue on the latest version?

**Comment by ramonmelo** [comment]
Fixed on the latest version.
