### ISSUE TITLE
Server authoritative movement in Bolt hackable?

### ISSUE THREAD

**Issue by DirtyHippy00** [BoltEngine/Bolt-Tracker#8]
There is no protection preventing a client from inserting multiple command inputs with the same server frame and different sequence.  The server merrily processes them all.  Clearly there was going to be some sort of check here on the server:

```
  int maxFrame = BoltCore._frame;
  int minFrame = maxFrame - (BoltCore._config.commandDelayAllowed + pingFrames);
```

in ReadInput in CommandChannel.  However, these two variables aren't used and Samizdat and I cannot find any code that prevents this from happening.

Essentially this means that Bolt's server authoritative movement is hackable, which was kind of the main value-add of Bolt in the first place.

**Comment by herpdederp** [comment]
We discussed this in chat and I said that this is probably not an issue but we'll look into this

**Comment by 0bytedna** [comment]
is this still an issue?

**Comment by DirtyHippy00** [comment]
I have tracked down an unrelated issue and have found that Bolt will queue inputs for the same frame as many times as you want - and it will execute them.

This happens on clients when you focus the editor after unfocusing it.  It blocks my editor for about a second, and then runs a ton of fixed updates trying to catch up which each submit SimulteController.  When you queue your inputs, internally Bolt queues BoltCore.serverFrame which is an estimated server frame and I guess when situations like this happen it submits with the same frame.

You will see each submitted input in ExecuteCommand for the same frame with IsFirstExecution on the client (and presumably on the server as well).

So someone clever could use this to speedhack by simply submitting a "forward" input for the same frame 10 times, for example.

I have trivially fixed the issue, client side, by simply not queuing inputs in SimulateController when I would be submitting an input for a frame already queued.  I'm not sure if this is ok or not but I haven't seen an issue.

A better solution would be to prevent bolt from even requesting for input for the same frame more than once - and also discarding queued inputs in bolt if their frame has already been queued.

**Comment by aleegs** [comment]
The solution by DirtyHippy can be bypassed i guess (it's client side).

Another fix would be adding a **server side** check on **ExecuteCommand** to not execute more than 1 command (or the same command) per frame. Not sure if this is a good approach but i tested it and worked agaisnt cheat engine.

**Comment by herpdederp** [comment]
@aleegs I think you mean per unique frame, not "have the server execute 1 command every server frame". I also tested this, but I think it will cause issues with latency/packetloss/etc so there has to be some leniency somewhere. We're currently looking at coming up with a new command system that won't have this issue in the first place.

**Comment by artfabrique** [comment]
any updates on this?

**Comment by herpdederp** [comment]
We're implementing a new command system atm that won't have this issue in the first place

**Comment by ramonmelo** [comment]
Starting from Bolt v1.2.4, it was implemented a new Command System that solves this type of issues.

It was added the option `Enable Frame Limit` to all commands, that limit the queue/execution to only one command per frame (on client and server). It's not necessary to set this to all commands, but it's there to be used on the most important ones.

Here are the tests executed to validate the implementation:
https://paper.dropbox.com/doc/Bolt-Hackable--AZ_AvMxHhByLgrKzILiZ~trzAQ-lZga0Tc8lL9WkY1crytjc
