### ISSUE TITLE
Build crashes on start-up when using Photon Bolt and building with IL2CPP

### ISSUE THREAD

**Issue by Yokogeri94** [BoltEngine/Bolt-Tracker#80]
###How to reproduce issue

**I've mailed a project which has a repro, if you create a build with it.**

Otherwise:

1. Create a new empty Unity project.
2. Install Photon Bolt to your project.
3. Make a really basic script which starts a server or connects to the server if client.
4. Create a build with .NET 4.x and IL2CPP
5. Play the build.
6. Game will crash upon start-up.

**This does not seem to happen when using Photon Bolt version 1.1.0.5.**

###Expected Behavior
Game should not crash when starting the build.

###Actual behavior
Game crashes upon starting the build.

###Configuration
Unity Version: 2018.1.6f1
Bolt Version: 1.1.0.8
Operating System: Windows 10 x64

**Comment by MildaGenius** [comment]
Hello,
I have probably the same problem.

Unity Version: 2018.1.6f1
.NET 4.x and IL2CPP
Target OS: iPad9.7 iOS 11.3

<img width="965" alt="screen shot 2018-07-31 at 07 29 27" src="https://user-images.githubusercontent.com/5381752/43454951-c4331c0e-94be-11e8-865e-a1046f9527ca.png">

**Comment by ramonmelo** [comment]
Hello All, thanks for your feedback, and sorry about the delay to respond on this.

Yes, we are aware of this issues, and it's mainly related to some parts of the networking stack that we use to make Bolt works that are not implemented in C++ by Unity. So when you build using IL2CPP, Bolt tries to use these code and raises the exceptions. We are already working on alternative solutions that have the same behavior but are implemented by the current stack.

**Comment by herpdederp** [comment]
Fixed with 1.2.0.0

**Comment by 0bytedna** [comment]
1.2.0.0? When is v1.1.0.10 gonna release?
