### ISSUE TITLE
Proxy creation messages are included each send tick until acked

### ISSUE THREAD

**Issue by DirtyHippy00** [BoltEngine/Bolt-Tracker#81]
Bolt currently will send entity proxy creation meta each send tick until the creation is acked (in EntityChannel::PackUpdate ()).

I.e. ProxyFlags.CREATE_REQUESTED is not cleared until the packet is delivered.

According to fholm the original intent was the creation message only be sent once, and then if acked the flag is cleared, and if the packet was lost then the creation message would need to be sent again.  This limits bandwidth/cpu for creating entities remotely (although it will potentially cause slightly longer delays for entity creation in edgy cases around packet loss).

**Comment by darvell** [comment]
This is an old issue but one that seems to be a problem, when we're working with 50 players and creating many a proxy, the amount of packets made is pretty high.

**Comment by DirtyHippy00** [comment]
What do you mean "the amount of packets made is pretty high"?  Bolt sends packets at a constant rate based on your sim rate/send rate and # connections.  The number of packets being sent does not vary beyond this.

**Comment by ramonmelo** [comment]
Thanks for your feedback.

Now the Entity creation waits for a failed request to send it again.
Available on the next release.
