### ISSUE TITLE
Customisable search paths for updating the Bolt prefab database

### ISSUE THREAD

**Issue by DaddyWalrus** [BoltEngine/Bolt-Tracker#83]
**Request for enhancement**
The ability to add a list of allowed search paths (say, in Bolt Settings) to limit the scope of the Bolt prefab database rebuild process would be very useful in supporting more efficient workflow on large projects.

**Reason for request**
When recompiling Bolt assemblies and updating the prefab database after making changes to Bolt assets, Bolt appears to search the entire assets folder for prefabs with a Bolt Entity component.

For small projects with very few folders and prefabs, this is not an issue: the recompile is fast and changes to Bolt assets can be made and tested relatively quickly.  Larger projects, especially those incorporating third party assets, might include many thousands of prefabs (cosmetic items, particle effects, etc.) which the developer never intends to use as Bolt entities.

There is currently no way to limit Bolt's recompile process to search only the folders which contain the prefabs the developer intends to use as Bolt entities, and this makes the recompile process very slow as Bolt iterates (potentially needlessly) over hundreds of folders and thousands of prefabs every time any changes are made.

**Configuration**
- Unity Version: 2018.2.1f1
- Bolt Version: 1.1.0.9
- Operating System: Windows 10 (1803 build 17134.228)

**Comment by herpdederp** [comment]
Added in 1.2.10
