### ISSUE TITLE
IProtocolTokens generate quite a bit of garbage when added up

### ISSUE THREAD

**Issue by cjddmut** [BoltEngine/Bolt-Tracker#85]
### How to reproduce issue
1. Use protocol tokens, especially in the command response stack

### Expected Behavior
Should generate less garbage. Either through restructure or using token pools.

### Actual behavior
Garbage! We use a lot of tokens and have a lot of garbage to show for it.

### Configuration
- Unity Version: 2017.3.0f3
- Bolt Version: 1.1.0.9
- Operating System: N/A
- Network Configuration: N/A

**Comment by ramonmelo** [comment]
Hello @cjddmut ,

We've implemented a pooling system for the `IProtocolTokens` that should help to reduce the memory usage when dealing with Tokens. It will be available on the next release.

Thanks for your feedback.
