### ISSUE TITLE
No callback when client attempts to connect to full server

### ISSUE THREAD

**Issue by JosephFerano** [BoltEngine/Bolt-Tracker#86]
### How to reproduce issue
1. Setup a server with a maximum amount of connections
2. Connect the maximum allowed amount of clients
3. Connect an extra client

### Expected Behavior
A callback should be received that indicates an error occurred, candidates include `ConnectFailed`, `ConnectRefused`, `Disconnected`, and `SessionConnectFailed`.

### Actual behavior
None of these callbacks are being raised. The client just continuously loops trying to connect to the same server.

### Configuration
- Unity Version: 2018.2.5f1 Linux
- Bolt Version: 1.1.0.9
- Operating System: Pop_OS! Ubuntu 17.10 x86_64 Linux 4.13.0-46-generic
- Network Configuration: Localhost , Photon Cloud

**Comment by ramonmelo** [comment]
Fixed on the next release.

In this case, you will receive the `SessionConnectFailed` callback.

Thanks for your feedback.
