### ISSUE TITLE
No UWP Support

### ISSUE THREAD

**Issue by markgrossnickle** [BoltEngine/Bolt-Tracker#87]
### How to reproduce issue
1. Download Bolt. Run a sample and attempt building for UWP

### Expected Behavior
Build should succeed. The Photon Bolt Free asset store page states it is perfect for AR/VR/MR but does not otherwise state which platforms it supports.  It should clearly state no UWP support (Hololens and Mixed Reality Devices).  Or you should add UWP support. :)

### Actual behavior
Build fails due to bolt.user.dll not being in a compatible assembly.

### Configuration
- Unity Version: 2018.1
- Bolt Version:  1.2.0.2
- Operating System: PC building to UWP
- Network Configuration: N/A

**Comment by Alexees** [comment]
Damn it, so much time spent to find a good cross platform networking alternative to UNET and again one that does not support UWP...

**Comment by herpdederp** [comment]
Due to new recommendations from Microsoft I don't think we'll be investing time in this

**Comment by Alexees** [comment]
> Due to new recommendations from Microsoft I don't think we'll be investing time in this

What are these new recommendations if I may ask?

**Comment by herpdederp** [comment]
The first reason people asked for UWP is due to being required for Microsoft Store, this is no longer the case.

https://news.xbox.com/en-us/2019/05/30/microsoft-approach-to-pc-gaming/?ocid=XGP_soc_omc_xbo_tw_Photo_lrn_5.30.1

In addition for the Creator's Program on Xbox which requires UWP, Online Multiplayer and Achievements are not allowed.

**Comment by Alexees** [comment]
I see. I was referring to Hololens 1 and 2 which use UWP the x32 or ARM32/ ARM64 way

**Comment by Pycorax** [comment]
As a fellow HoloLens developer, I find this quite disappointing. A solution like Bolt seemed perfect for the use case of many types of HoloLens applications. We have to resort to using PUN instead which while works, is not ideal due to the requirement for internet connectivity.

**Comment by AqlaSolutions** [comment]
Hey, it seems that UWP build on Unity allows to use full .NET Framework runtime which means modern garbage collection. So UWP build would be a good choice for server-side unity.
