### ISSUE TITLE
The type or namespace name `GlobalEventListener' does not exist in the namespace `Bolt'

### ISSUE THREAD

**Issue by moXier1337** [BoltEngine/Bolt-Tracker#88]
### How to reproduce issue
1. Install Photon Bolt from the asset store
2. Hosting should be EU with nat punchtrough
3. Install core packages

### Expected Behavior
https://gyazo.com/b6f7bcaa962a8e6a38949b3e9574ee28

### Actual behavior
It wont function, gives the error

Assets/bolt/scripts/BoltRuntimeConfigs.cs(5,40): error CS0234: The type or namespace name `GlobalEventListener' does not exist in the namespace `Bolt'. Are you missing an assembly reference?

Also when you hit compile assembly it prints out
IndexOutOfRangeException: Array index is out of range.
BoltEditorUtilsInternal.CSharpIdentifier (System.String value)
BoltCompiler.CompileMaps (.BoltCompilerOperation op)
BoltCompiler.Run (.BoltCompilerOperation op)
BoltUserAssemblyCompiler.Run ()
UnityEngine.Debug:LogException(Exception)
BoltUserAssemblyCompiler:Run()
BoltMenuItems:RunCompiler()
BoltWizardWindow:InitialSetup() (at Assets/bolt/scripts/editor/BoltWizardWindowUtils.cs:170)
BoltWizardWindow:Install(BoltPackage) (at Assets/bolt/scripts/editor/BoltWizardWindow.cs:885)
<DrawInstallOption>c__AnonStorey1:<>m__0() (at Assets/bolt/scripts/editor/BoltWizardWindow.cs:787)
BoltWizardWindow:DrawStepOption(Texture2D, GUIContent, GUIContent, Nullable`1, Action) (at Assets/bolt/scripts/editor/BoltWizardWindow.cs:838)
BoltWizardWindow:DrawInstallOption(BoltInstalls) (at Assets/bolt/scripts/editor/BoltWizardWindow.cs:792)
BoltWizardWindow:DrawSetupBolt() (at Assets/bolt/scripts/editor/BoltWizardWindow.cs:482)
BoltWizardWindow:DrawContent() (at Assets/bolt/scripts/editor/BoltWizardWindow.cs:441)
BoltWizardWindow:OnGUI() (at Assets/bolt/scripts/editor/BoltWizardWindow.cs:417)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

### Configuration
- Unity Version: 2018.2.6f1
- Bolt Version: 1.2.0.2
- Operating System: Windows 10
- Network Configuration: Default configuration, photon cloud eu, with nat punchthrough

**Comment by moXier1337** [comment]
Btw, I've sent email's, havent really gotten any reply, the ticked id is 23425.

**Comment by moXier1337** [comment]
Btw, it seems to be working better with version 2017.4.12f1 LTD

**Comment by ramonmelo** [comment]
Are updating your project with the latest version or testing on an empty project?

Please, take a look at: https://doc.photonengine.com/en-us/bolt/current/setup/upgrading

**Comment by herpdederp** [comment]
Make sure you install core package and compile assembly. Let us know if there are still issues after doing that.
