### ISSUE TITLE
Compiling Bolt with deleted scenes in build settings will throw exception.

### ISSUE THREAD

**Issue by alexd-eps** [BoltEngine/Bolt-Tracker#89]
### How to reproduce issue
1. Ensure there are deleted scenes referenced by editor build settings.
2. Compile Bolt.

### Expected Behavior
Bolt should compile.

### Actual behavior
Bolt compiler throws an exception.

### Configuration
- Unity Version: 2018.2.6f1
- Bolt Version: 1.1.0.9
- Operating System: Windows

Note this has been observed on multiple Bolt and Unity versions.

This issue is easy to fix / avoid but occasionally crops up on Discord chat.

**Comment by ramonmelo** [comment]
Thanks for the feedback.

Fixed on the next release.
