### ISSUE TITLE
State callback doesnt fire

### ISSUE THREAD

**Issue by buzzard2** [BoltEngine/Bolt-Tracker#90]
### How to reproduce issue
Create state property with type "Entity" and add callback to it.

### Expected Behavior
after property value changes callback fires

### Actual behavior
After value is changed from NULL to Entity1 or Entity1 to NULL callback fires. If value is changed from Entity1 to Entity2 callback doesnt fire

### Configuration
- Unity Version: 2018.2
- Bolt Version: 1.2.0.2
- Operating System: Win10

**Comment by buzzard2** [comment]
Any reaction? Is it a bug? Will it get fixed?

**Comment by DirtyHippy00** [comment]
There are bugs with the Entity property type.  I filed the (different) bug I found a while back.  I wasn't aware of this one, but my suggestion would be to use a NetworkId type instead and then just find the entity yourself with FindEntity ().  Under the hood Entity property is just a wrapper on top of network id.

**Comment by ramonmelo** [comment]
Thanks for the feedback.

Fixed on the next release.
