### ISSUE TITLE
error in bolt getting-started docs bolt-105-objects-and-arrays

### ISSUE THREAD

**Issue by VonHirsch** [BoltEngine/Bolt-Tracker#91]
### How to reproduce issue
1. goto https://doc.photonengine.com/en-us/bolt/current/getting-started/bolt-105-objects-and-arrays

### Expected Behavior
Weapon should change from cylinder->capsule->sphere

### Actual behavior
Weapon indexes are randomized which is confusing

### Fix
Change code line:

> state.WeaponArray[i].WeaponId = Random.Range(0, WeaponObjects.Length - 1);

to:

> state.WeaponArray[i].WeaponId = i;

(this code appears twice on the page so should be corrected twice)

**Comment by ramonmelo** [comment]
Fixed. Thanks for the feedback.
