### ISSUE TITLE
spellings RobotBehaviour and RobotBehavior are used interchangeably

### ISSUE THREAD

**Issue by VonHirsch** [BoltEngine/Bolt-Tracker#92]
### How to reproduce issue
1. goto https://doc.photonengine.com/en-us/bolt/current/getting-started/bolt-106-animations

spellings RobotBehaviour and RobotBehavior are used interchangeably in the tutorial

**Comment by herpdederp** [comment]
"https://doc.photonengine.com/en-us/bolt/current/getting-started/bolt-103-properties-and-callbacks -- it says to create a script called "CubeBehaviour" however the example code uses "CubeBehavior" (without a "u") which stops things working"
