### ISSUE TITLE
SetTransform(state.MyTransform, myTransform, childOfMyTransform) not sync in clients if entity stationary in server

### ISSUE THREAD

**Issue by vlab22** [BoltEngine/Bolt-Tracker#94]
Maybe as #5 

### How to reproduce issue
1. New Project, install Photon Bolt Free, Bolt Wizard set app ID, install bolt core package, create a new scene named Scene1, add it to Build Settings scenes list, remove others scenes (SampleScene etc follow bolt's docs)
2. In Scene1, create a empty GameObject named "CubeParent", create a 3D Cube as a child of CubeParent named Cube, let them with ZERO position and rotation
3. Create a GameObject named "CubeState Prefab", add BoltEntity component, set state to ICubeState, drag to Asset folder to create the prefab, delete gameobject in scene, bolt compile, set options as
![image](https://user-images.githubusercontent.com/1412924/48835852-96a2f600-ed57-11e8-854b-8db10ef5e227.png)
4. Create a C# CubeStateBv.cs and add to CubeState Prefab.
```csharp
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CubeStateBv : Bolt.EntityBehaviour<ICubeState>
{
	public Transform cubeP;
	public Transform cubeR;

	public override void Attached ()
	{
		cubeP = GameObject.Find("CubeParent").transform;
		cubeR = cubeP.Find("Cube");

		state.SetTransforms(state.CubeTransform, cubeP, cubeR);
	}
}
```
5. Create a C# GeneralServerBoltCallback.cs
```csharp
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[BoltGlobalBehaviour (BoltNetworkModes.Server)]
public class GeneralServerBoltCallback : Bolt.GlobalEventListener
{
	public override void SceneLoadLocalDone (string map)
	{
		StartCoroutine (SceneLoadLocalDoneRoutine (map));
	}

	private IEnumerator SceneLoadLocalDoneRoutine (string map)
	{
		yield return new WaitForSeconds (5);
		var cubeEntity = BoltNetwork.Instantiate (BoltPrefabs.CubeState_Prefab);
		var cubeBv = cubeEntity.GetComponent<CubeStateBv>();
		
		cubeBv.cubeP.transform.position = Vector3.forward * 15 + Vector3.right * 2;
	}
}
```
6. Bolt Scenes -> Scene1 -> Debug Start

### Expected Behavior

1. In Server, scene loaded, after 5 seconds server instantiates a "CubeState Prefab" and sets cubeP position to (2 , 0 ,15),
2. In Server, Bolt sets CubeState state.CubeTransform to X:2.00 Y:0.00 Z:15.00 / X:0.00 Y:0.00 Z:0.00(R: Cube)
3. In Client, after connect, scene loaded, CubeState attached, state.CubeTransform **syncs** with server and cubeP moves to desired position
4. In Server (editor), move cubeP with gizmos
5. In Client, cubeP will move too, state.CubeTransform synchronized

### Actual behavior
1. In Server, scene loaded, after 5 seconds server instantiates a "CubeState Prefab" and sets cubeP position to (2 , 0 ,15),
2. In Server, Bolt sets CubeState state.CubeTransform to X:2.00 Y:0.00 Z:15.00 / X:0.00 Y:0.00 Z:0.00(R: Cube)
3. In Client, after connect, scene loaded, CubeState attached, state.CubeTransform **DOESN'T** syncs with server and cubeP does **NOT** move to desired position, stay at (0,0,0) and state.CubeTransform is X:0.00 Y:0.00 Z:0.00 / X:0.00 Y:0.00 Z:0.00(R: Cube)
4. In Server (editor), moves cubeP with gizmos
5. In Client, cubeP **WILL** move too, state.CubeTransform synchronized
6. Go further and start another client, after CubeState attached, state.CubeTransform **NOT** synchronized, cubeP stays at (0,0,0)

So, when a entity is attached in client and it's "stationary" in server (owner), the current server position will not sync until _CubeParent_ moves in server.
This strange behavior not happens if we not separate CubeState Prefabs from other transforms.
If it's like
- CubeState
-- Cube
And use _SetTransform(state.CubeTransform, transform, cube)_ and then move CubeState in server, everything works fine as long as cube is child of CubeState

Project attached
[BoltTest3.zip](https://github.com/BoltEngine/Bolt-Tracker/files/2603966/BoltTest3.zip)

### Configuration
- Unity Version: 2018.2.12f1
- Bolt Version: 1.2.0.3
- Operating System: Win10 1803 x64

**Comment by ramonmelo** [comment]
Hello @vlab22,

You are interpreting `SetTransforms` incorrectly. If you look at the [API Docs](https://doc-api.photonengine.com/en/bolt/current/interface_bolt_1_1_i_state.html#a4d37b45833222dea444bc387b4792781) you will see that the last parameter is named `render`, and it's used to smooth the motion of the entity transform. You can read more about this topic [here](https://doc.photonengine.com/en-us/bolt/current/in-depth/temporal-anti-aliasing).

But the issue of using another `Transform` (child or not of the `GameObject` with the `Bolt Entity` component) as you did with the `CubeParent` not being synced until the first update is fixed on the next release.

Thanks for the feedback.
