### ISSUE TITLE
Bolt not friendly to assembly definitions

### ISSUE THREAD

**Issue by jswigart** [BoltEngine/Bolt-Tracker#95]
Assembly definition files are a mechanism in newer versions of unity to allow you to break up your project into a number of assemblies, to reduce compilation speed, etc. 

https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html

With this system it's common practice to break large third party assets into their own assembly since they are rarely modified.

Bolt doesn't appear to be friendly to being put in its own assembly and functioning with game code that is in another assembly

### How to reproduce issue
1. Create an assembly definition file in the bolt folder
2. Create a global GlobalEventListener subclass in another assembly
3. Start a server or client instance

### Expected Behavior
I would expect that GlobalEventListener subclasses would be found and instantiated across all loaded assemblies

### Actual behavior
The GlobalEventListener subclasses you have in assemblies other than the bolt assembly will not be instantiated.

### Configuration
- Unity Version: 2018.2.11f1
- Bolt Version: 1.2.0.3
- Operating System: Win10

Assuming this is a simple fix of searching for these listeners across all assemblies and not just the current one.

**Comment by vladnau89** [comment]
Hello! I have the same problem. You can fix it : 
at BoltLauncher.cs method GetGlobalBehaviourTypes()

replace Assembly asm = Assembly.GetExecutingAssembly();

**Comment by ramonmelo** [comment]
Fixed on the next release.
Thanks for your feedback!

**Comment by melMass** [comment]
> Fixed on the next release.
> Thanks for your feedback!

Can I ask how it works?
I want to add custom Units from a custom package, but there is nothing related to Bolt or Ludiq in the Assembly References dropdown 👶

**Comment by herpdederp** [comment]
> > Fixed on the next release.
> 
> > Thanks for your feedback!
> 
> 
> 
> Can I ask how it works?
> 
> I want to add custom Units from a custom package, but there is nothing related to Bolt or Ludiq in the Assembly References dropdown 👶 

Photon Bolt is unrelated to Ludiq and visual scripting.

**Comment by melMass** [comment]
Oops thanks, not obvious at all tbh
