### ISSUE TITLE
Debug Start settings launch improvement

### ISSUE THREAD

**Issue by jswigart** [BoltEngine/Bolt-Tracker#96]
I'd like to make a couple requests to the debug start UI/functionality to improve upon them.

The 'Debug Start' button currently does a standalone build for launching the clients. This can be a time consuming process, so I'd like to propose the following 2 minor improvements to this window.

1) Add a 'Debug Start Previous' to do the launch by itself, and skip the build.
2) Add a 'Debug Launch ScriptsOnly' so that it does the build, however it uses the BuildOptions.BuildScriptsOnly option, to skip the time consuming asset build process(provided you've done a full build at least once prior)

https://docs.unity3d.com/ScriptReference/BuildOptions.BuildScriptsOnly.html

Alternately(and I would prefer this frankly), make a 'Full Build' and 'Scripts Only Build' entirely separate buttons, and have the Debug start merely use whatever build was performed last.

**Comment by ramonmelo** [comment]
Thanks for your feedback.

We've made some changes to the `Bolt Debug Scenes` window to accomplish some of these actions.
It will be available on the next release.

![Screen Shot 2020-06-26 at 15 32 59](https://user-images.githubusercontent.com/873570/85890870-93d67580-b7c4-11ea-951f-e962d8f511e3.png)
