### ISSUE TITLE
Dynamically added EntityBehaviour do not work

### ISSUE THREAD

**Issue by jswigart** [BoltEngine/Bolt-Tracker#97]
### How to reproduce issue
1. Client Side: Instantiate an entity
2. Client Side: Add a EntityBehaviour derived component to the object
3. Client Side: Call entity.AddEventListener(the component we just added)
4. Observe the EntityBehaviour isn't invoked properly, such as SimulateOwner

### Expected Behavior
I would expect, especially with the presence of an entity.AddEventListener, that EntityBehavior components could be added at runtime, rather than requiring being on the prefab

### Actual behavior
The SimulateOwner, etc functions do not get called on the dynamically added EntityBehaviour, only the default ones

### Configuration
- Unity Version: 2018.2.11f1
- Bolt Version: 1.2.0.3
- Operating System: Win10

**Comment by fholm** [comment]
Working as intended

**Comment by jswigart** [comment]
What's the purpose of entity.AddEventListener then?
